# Debug Scraper Antara Jatim

Local HTML first, then optional live list/article checks. Output list CSV: `csv/antara_jatim_list_debug.csv`.

In [1]:
from pathlib import Path
import sys
import importlib
from urllib.parse import urljoin

import pandas as pd
from bs4 import BeautifulSoup

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'scrapers').exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scrapers.common import cutoff_date, parse_date, records_to_df
import scrapers.antarajatim as scraper
scraper = importlib.reload(scraper)

pd.set_option('display.max_rows', 200)
pd.set_option('display.max_colwidth', 160)

SAMPLE_PATH = PROJECT_ROOT / 'html_samples/antarajatim.txt'
OUTPUT_PATH = PROJECT_ROOT / 'csv/antara_jatim_list_debug.csv'
MAX_PAGES = 200
TITLE_LIMIT = 90
cutoff = cutoff_date()

print('project:', PROJECT_ROOT)
print('module:', scraper.__file__)
print('sample:', SAMPLE_PATH)
print('cutoff:', cutoff.date())

project: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project
module: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project/scrapers/antarajatim.py
sample: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project/html_samples/antarajatim.txt
cutoff: 2026-02-28

In [2]:

def short_title(value, limit=TITLE_LIMIT):
    text = '' if pd.isna(value) else str(value).strip()
    return text if len(text) <= limit else text[: limit - 3] + '...'


def ensure_debug_columns(df):
    df = df.copy()
    if 'page_num' not in df.columns:
        df['page_num'] = pd.NA
    if 'published_date' not in df.columns:
        df['published_date'] = None
    df['published_dt'] = df['published_date'].apply(parse_date)
    return df


def print_debug_rows(df):
    for _, row in df.iterrows():
        page = row.get('page_num')
        page_text = '---' if pd.isna(page) else f'{int(page):03d}'
        date_text = row.get('published_date')
        date_text = 'None' if pd.isna(date_text) else str(date_text)
        print(f"page={page_text} | date={date_text} | title={short_title(row.get('title'))}")


def audit_list(df):
    df = ensure_debug_columns(df)
    print('total rows:', len(df))
    if len(df) == 0:
        print('No rows found.')
        return df
    print('first page:', df['page_num'].dropna().min() if df['page_num'].notna().any() else None)
    print('last page:', df['page_num'].dropna().max() if df['page_num'].notna().any() else None)
    print('newest date:', df['published_dt'].max())
    print('oldest date:', df['published_dt'].min())
    print('cutoff date:', cutoff)
    print('reached cutoff:', bool((df['published_dt'].dropna() < cutoff).any()))
    print('null parsed dates:', int(df['published_dt'].isna().sum()))

    print('\nrows per month:')
    display(
        df.assign(month=df['published_dt'].dt.to_period('M').astype(str))
        .groupby('month', dropna=False)
        .size()
        .reset_index(name='count')
    )

    print('\nrows per page:')
    display(
        df.groupby('page_num', dropna=False)
        .agg(rows=('url', 'count'), newest=('published_dt', 'max'), oldest=('published_dt', 'min'))
        .reset_index()
        .tail(80)
    )
    return df

In [3]:

def parse_local_list(html_text):
    soup = BeautifulSoup(html_text, 'html.parser')
    rows = []
    for card in soup.select('.card__post'):
        title_tag = card.select_one('.card__post__title h2 a[href]')
        date_tag = card.select_one('.card__post__author-info')
        image_tag = card.select_one('img')
        if not title_tag:
            continue
        rows.append({
            'page_num': 1,
            'list_page_url': scraper.BASE_URL,
            'title': title_tag.get_text(' ', strip=True),
            'url': urljoin(scraper.BASE_URL, title_tag['href']),
            'published_date': date_tag.get_text(' ', strip=True) if date_tag else None,
            'image_url': (image_tag.get('data-src') or image_tag.get('src')) if image_tag else None,
        })
    return records_to_df(rows)

## Local HTML list parse

In [4]:
html_text = SAMPLE_PATH.read_text(errors='replace')
local_df = parse_local_list(html_text)
local_df = ensure_debug_columns(local_df)
print_debug_rows(local_df)
local_df = audit_list(local_df)

page=001 | date=26 Juni 2026 23:03 | title=Ribuan umat Muslim di Malang doakan Prabowo dikuatkan pimpin bangsa
page=001 | date=21 jam lalu | title=Liburan di kawasan tiga pantai di Malang
page=001 | date=27 Juni 2026 20:39 | title=PDI Perjuangan Kota Malang dekatkan diri dengan anak muda lewat kompetisi e-sport
page=001 | date=27 Juni 2026 18:51 | title=Menkop siapkan koperasi pesantren jadi pemasok Koperasi Merah Putih
page=001 | date=27 Juni 2026 15:45 | title=Pemkab Malang komunikasikan realisasi hilirisasi garam dengan pusat
page=001 | date=26 Juni 2026 16:47 | title=Peneliti UB temukan empat spesies kumbang baru
page=001 | date=26 Juni 2026 09:48 | title=Pemkot Malang: Sejak 2025 tak ada kasus pemasungan disabilitas mental
page=001 | date=25 Juni 2026 20:34 | title=DPRD Malang dorong SiLPA Rp303 Miliar untuk pembiayaan UHC
page=001 | date=25 Juni 2026 16:50 | title=Polres Malang bangun sumur bor di tujuh desa antisipasi dampak kemarau
page=001 | date=25 Juni 2026 16:10 | title=Dinsos Kota Malang: 130 calon murid SRMA terdata pendamping PKH
total rows: 10
first page: 1
last page: 1
newest date: 2026-06-28 15:15:17.316386
oldest date: 2026-06-25 16:10:00
cutoff date: 2026-02-28 12:15:09.228848
reached cutoff: False
null parsed dates: 0

rows per month:

     month  count
0  2026-06     10

rows per page:

   page_num  rows                     newest              oldest
0         1    10 2026-06-28 15:15:17.316386 2026-06-25 16:10:00

## Live list scrape

In [5]:
live_df = scraper.scrape_list(cutoff, max_pages=MAX_PAGES)
live_df = ensure_debug_columns(live_df)
print_debug_rows(live_df)
live_df = audit_list(live_df)

Scraping Antara Jatim page 1: https://jatim.antaranews.com/kabar-jatim/malang-raya
Scraping Antara Jatim page 2: https://jatim.antaranews.com/kabar-jatim/malang-raya/2
Scraping Antara Jatim page 3: https://jatim.antaranews.com/kabar-jatim/malang-raya/3
Scraping Antara Jatim page 4: https://jatim.antaranews.com/kabar-jatim/malang-raya/4
Scraping Antara Jatim page 5: https://jatim.antaranews.com/kabar-jatim/malang-raya/5
Scraping Antara Jatim page 6: https://jatim.antaranews.com/kabar-jatim/malang-raya/6
Scraping Antara Jatim page 7: https://jatim.antaranews.com/kabar-jatim/malang-raya/7
Scraping Antara Jatim page 8: https://jatim.antaranews.com/kabar-jatim/malang-raya/8
Scraping Antara Jatim page 9: https://jatim.antaranews.com/kabar-jatim/malang-raya/9
Scraping Antara Jatim page 10: https://jatim.antaranews.com/kabar-jatim/malang-raya/10
Scraping Antara Jatim page 11: https://jatim.antaranews.com/kabar-jatim/malang-raya/11
Scraping Antara Jatim page 12: https://jatim.antaranews.com/kabar-jatim/malang-raya/12
Scraping Antara Jatim page 13: https://jatim.antaranews.com/kabar-jatim/malang-raya/13
Scraping Antara Jatim page 14: https://jatim.antaranews.com/kabar-jatim/malang-raya/14
Scraping Antara Jatim page 15: https://jatim.antaranews.com/kabar-jatim/malang-raya/15
Scraping Antara Jatim page 16: https://jatim.antaranews.com/kabar-jatim/malang-raya/16
Scraping Antara Jatim page 17: https://jatim.antaranews.com/kabar-jatim/malang-raya/17
Scraping Antara Jatim page 18: https://jatim.antaranews.com/kabar-jatim/malang-raya/18
Scraping Antara Jatim page 19: https://jatim.antaranews.com/kabar-jatim/malang-raya/19
Scraping Antara Jatim page 20: https://jatim.antaranews.com/kabar-jatim/malang-raya/20
Scraping Antara Jatim page 21: https://jatim.antaranews.com/kabar-jatim/malang-raya/21
Scraping Antara Jatim page 22: https://jatim.antaranews.com/kabar-jatim/malang-raya/22
Scraping Antara Jatim page 23: https://jatim.antaranews.com/kabar-jatim/malang-raya/23
Scraping Antara Jatim page 24: https://jatim.antaranews.com/kabar-jatim/malang-raya/24
Scraping Antara Jatim page 25: https://jatim.antaranews.com/kabar-jatim/malang-raya/25
Scraping Antara Jatim page 26: https://jatim.antaranews.com/kabar-jatim/malang-raya/26
Scraping Antara Jatim page 27: https://jatim.antaranews.com/kabar-jatim/malang-raya/27
Scraping Antara Jatim page 28: https://jatim.antaranews.com/kabar-jatim/malang-raya/28
Scraping Antara Jatim page 29: https://jatim.antaranews.com/kabar-jatim/malang-raya/29
Scraping Antara Jatim page 30: https://jatim.antaranews.com/kabar-jatim/malang-raya/30
Scraping Antara Jatim page 31: https://jatim.antaranews.com/kabar-jatim/malang-raya/31
Scraping Antara Jatim page 32: https://jatim.antaranews.com/kabar-jatim/malang-raya/32
Scraping Antara Jatim page 33: https://jatim.antaranews.com/kabar-jatim/malang-raya/33
Scraping Antara Jatim page 34: https://jatim.antaranews.com/kabar-jatim/malang-raya/34
Scraping Antara Jatim page 35: https://jatim.antaranews.com/kabar-jatim/malang-raya/35
Scraping Antara Jatim page 36: https://jatim.antaranews.com/kabar-jatim/malang-raya/36
Scraping Antara Jatim page 37: https://jatim.antaranews.com/kabar-jatim/malang-raya/37
Scraping Antara Jatim page 38: https://jatim.antaranews.com/kabar-jatim/malang-raya/38
page=001 | date=22 jam lalu | title=Liburan di kawasan tiga pantai di Malang
page=001 | date=27 Juni 2026 20:39 | title=PDI Perjuangan Kota Malang dekatkan diri dengan anak muda lewat kompetisi e-sport
page=001 | date=27 Juni 2026 18:51 | title=Menkop siapkan koperasi pesantren jadi pemasok Koperasi Merah Putih
page=001 | date=27 Juni 2026 15:45 | title=Pemkab Malang komunikasikan realisasi hilirisasi garam dengan pusat
page=001 | date=26 Juni 2026 23:03 | title=Ribuan umat Muslim di Malang doakan Prabowo dikuatkan pimpin bangsa
page=001 | date=26 Juni 2026 16:47 | title=Peneliti UB temukan empat spesies kumbang baru
page=001 | date=26 Juni 2026 09:48 | title=Pemkot Malang: Sejak 2025 tak ada kasus pemasungan disabilitas mental
page=001 | date=25 Juni 2026 20:34 | title=DPRD Malang dorong SiLPA Rp303 Miliar untuk pembiayaan UHC
page=001 | date=25 Juni 2026 16:50 | title=Polres Malang bangun sumur bor di tujuh desa antisipasi dampak kemarau
page=001 | date=25 Juni 2026 16:10 | title=Dinsos Kota Malang: 130 calon murid SRMA terdata pendamping PKH
page=002 | date=25 Juni 2026 13:47 | title=Realisasi APBN untuk ketahanan pangan di Jatim
page=002 | date=24 Juni 2026 19:24 | title=Polres Malang tangkap dua ASN gadungan tersangka penipuan UMKM
page=002 | date=23 Juni 2026 20:17 | title=Polisi tangani kecelakaan truk di Malang akibatkan satu korban tewas
page=002 | date=23 Juni 2026 15:54 | title=BKAD Kota Malang target sertifikasi aset daerah tuntas 2-3 tahun
page=002 | date=22 Juni 2026 19:48 | title=Sebanyak 50 band dan musisi akan tampil di Partilibur Caravan 2026
page=002 | date=22 Juni 2026 18:47 | title=Pameran seni instalasi bertajuk Tanah Air
page=002 | date=22 Juni 2026 18:43 | title=Gelaran Batu Greenation Fest 2026
page=002 | date=22 Juni 2026 18:29 | title=Pemkot Malang siapkan layanan psikologi klinis gratis di puskesmas
page=002 | date=20 Juni 2026 16:45 | title=Massa aksi komitmen kawal realisasi target penerima manfaat MBG
page=002 | date=20 Juni 2026 15:08 | title=Anggota DPR RI tegaskan pemerintah tidak antikritik soal program MBG
page=003 | date=20 Juni 2026 12:17 | title=Massa aksi di Malang dukung keberlanjutan Program MBG
page=003 | date=19 Juni 2026 22:55 | title=Pemkot Malang: Nobar Piala Dunia kuatkan silaturahim dengan warga
page=003 | date=19 Juni 2026 20:51 | title=Pemkot Malang: Kesetaraan hak kelompok rentan bagian arah pembangunan
page=003 | date=19 Juni 2026 19:38 | title=ASN Pemkot Malang kenakan jersi peserta Piala Dunia saat jam kerja
page=003 | date=19 Juni 2026 16:50 | title=Diskominfo Kota Malang lindungi pelajar SRMP dari judol lewat SAPULIDI
page=003 | date=19 Juni 2026 16:26 | title=Tradisi Mapag Arum Jenang Suro di Malang
page=003 | date=19 Juni 2026 16:22 | title=Pelayanan publik bernuansa Piala Dunia
page=003 | date=19 Juni 2026 06:33 | title=BB TNBTS amankan empat pendaki ilegal Gunung Semeru
page=003 | date=18 Juni 2026 06:25 | title=Paradigma pertahanan negara mengalami transformasi besar
page=003 | date=17 Juni 2026 21:33 | title=DPRD Kota Malang tampung aspirasi mahasiswa
page=004 | date=17 Juni 2026 17:42 | title=Pemkot Malang larang ASN main medsos saat jam kerja demi jaga layanan
page=004 | date=16 Juni 2026 16:52 | title=TNBTS tangkap 13 orang diduga pendaki ilegal Gunung Semeru
page=004 | date=15 Juni 2026 20:43 | title=Pemkot Malang sebut rehabilitasi jalan Pasar Gadang tuntas 172 hari
page=004 | date=15 Juni 2026 14:48 | title=Pemkot Malang sebut empat pasar rakyat masuk prioritas revitalisasi
page=004 | date=14 Juni 2026 19:22 | title=BMKG perkirakan kemarau di Malang Raya hingga Oktober-November 2026
page=004 | date=14 Juni 2026 16:38 | title=Pemkot Malang perketat pengawasan izin operasional SPPG
page=004 | date=14 Juni 2026 07:39 | title=Dudung tinjau Sekolah Rakyat di Malang, bantu anak putus sekolah
page=004 | date=13 Juni 2026 23:00 | title=MA rawat integritas insan peradilan lewat kejuaraan tenis beregu
page=004 | date=13 Juni 2026 20:53 | title=Pemkot Malang: Perubahan alamat jadi kendala SPMB jalur domisili
page=004 | date=13 Juni 2026 16:14 | title=Perayaan hari skateboard di Malang
page=005 | date=13 Juni 2026 11:59 | title=Mahasiswa UMM kembangkan inovasi mesin pencuci singkong untuk UMKM
page=005 | date=12 Juni 2026 22:50 | title=KSP tanamkan semangat pantang menyerah ke murid Sekolah Rakyat Malang
page=005 | date=12 Juni 2026 05:02 | title=Universitas Brawijaya optimalkan ICSDGs 2026 jadi wadah gagas ide pemenuhan SDGs
page=005 | date=11 Juni 2026 21:59 | title=Pemkot Malang pertimbangkan gunakan  EV usai harga Pertamax naik
page=005 | date=11 Juni 2026 21:15 | title=UIN Maliki Malang cetak ilmuwan berjiwa ulama di era digital
page=005 | date=11 Juni 2026 19:03 | title=OJK Malang gandeng ILO perkuat akses peternak sapi perah lewat ERP
page=005 | date=11 Juni 2026 16:38 | title=Pemkot Malang: Hasil Sensus Ekonomi ciptakan kebijakan tepat sasaran
page=005 | date=10 Juni 2026 17:49 | title=Pemkot Malang bantu tingkatkan efektivitas distribusi MBG
page=005 | date=10 Juni 2026 15:35 | title=Pemkab Malang sebut "blankspot" sinyal tersisa 85 titik di 2026
page=005 | date=9 Juni 2026 20:01 | title=Bakorwil III: Pembangunan selatan Jatim tingkatkan kualitas SDM
page=006 | date=9 Juni 2026 18:35 | title=Pemkot Malang salurkan beasiswa untuk pelajar dan mahasiswa tak mampu
page=006 | date=8 Juni 2026 20:33 | title=Universitas Brawijaya tambah tiga guru besar lintas keilmuan
page=006 | date=8 Juni 2026 14:02 | title=Pemkot Batu: Pertanian cerdas terintegrasi guna putus rantai tengkulak
page=006 | date=7 Juni 2026 20:56 | title=Polres Batu prioritaskan tindak delapan pelanggaran selama Operasi Patuh
page=006 | date=7 Juni 2026 20:55 | title=Pemkot Batu optimalkan "green house" cegah "bediding"
page=006 | date=7 Juni 2026 15:49 | title=Simulasi penanggulangan kebakaran di Malang
page=006 | date=6 Juni 2026 20:33 | title=Polres Malang bentuk budaya tertib berlalu lintas lewat Operasi Patuh
page=006 | date=4 Juni 2026 19:01 | title=UNIKAMA-Grand Mercure Malang olah sampah makanan jadi pakan ternak
page=006 | date=4 Juni 2026 18:49 | title=Seragam gratis di Malang turun dari 13 ribu jadi 4 ribu siswa
page=006 | date=4 Juni 2026 16:00 | title=BMKG beberkan penyebab terjadinya "bediding" di Malang Raya
page=007 | date=3 Juni 2026 20:17 | title=Disdikbud Kota Malang jamin transparansi informasi SPMB 2026
page=007 | date=3 Juni 2026 19:12 | title=Pemkot Malang cek kesehatan masyarakat kontak erat dengan pasien TBC
page=007 | date=3 Juni 2026 18:21 | title=Kejari Kota Malang buka posko aduan guna cegah penyimpangan program MBG
page=007 | date=3 Juni 2026 17:16 | title=SAR evakuasi pendaki terperosok jurang Gunung Semeru
page=007 | date=2 Juni 2026 22:30 | title=Polisi hentikan penyidikan kasus pengeroyokan wisatawan di Malang
page=007 | date=2 Juni 2026 21:33 | title=Polresta Malang imbau masyarakat manfaatkan layanan SIM digital
page=007 | date=2 Juni 2026 16:09 | title=Pemkot Malang siapkan pendamping, cegah kendala pendaftaran SPMB
page=007 | date=2 Juni 2026 15:24 | title=Tera ulang timbangan pedagang pasar di Malang
page=007 | date=1 Juni 2026 06:54 | title=2.316 wisatawan kunjungi Ranu Regulo di libur Idul Adha hingga Waisak
page=007 | date=31 Mei 2026 23:00 | title=PHRI Kota Batu catat okupansi hotel 80 persen saat libur Waisak
page=008 | date=31 Mei 2026 21:22 | title=Wali Kota Malang: Pengisian kekosongan jabatan tunggu verifikasi BKN
page=008 | date=30 Mei 2026 22:13 | title=Perbaikan akses jalan Pasar Gadang Kota Malang tunjang perekonomian
page=008 | date=30 Mei 2026 21:25 | title=Pemkot Malang proyeksikan "job fair" 2026 serap 3.000 lulusan SMA/SMK
page=008 | date=30 Mei 2026 16:53 | title=6.218 penumpang padati Stasiun Malang jelang libur Waisak
page=008 | date=30 Mei 2026 16:50 | title=BB TNBTS evaluasi keamanan transportasi usai kecelakaan di jalur Bromo
page=008 | date=29 Mei 2026 22:09 | title=Ombudsman RI-Pemkot Malang cegah malaadministrasi pelayanan publik
page=008 | date=29 Mei 2026 16:51 | title=Pemprov Jatim kaji penambahan koridor TransJatim Malang Raya
page=008 | date=29 Mei 2026 15:10 | title=Khofifah minta kepala daerah proaktif cek perkembangan harga sembako
page=008 | date=28 Mei 2026 20:30 | title=Pemkot Malang target tempat relokasi pedagang Pasar Gadang ranpung Juni
page=008 | date=28 Mei 2026 19:10 | title=Terminal Arjosari Malang layani 8.652 penumpang libur Idul Adha
page=009 | date=28 Mei 2026 14:01 | title=Pemkot Malang kembangkan wisata melalui skema integrasi kawasan
page=009 | date=27 Mei 2026 20:46 | title=KAI layani 5.460 penumpang di Stasiun Malang selama libur Idul Adha
page=009 | date=27 Mei 2026 16:53 | title=Pemkot Malang mendelegasikan pengelolaan tiga lokasi JPL ke KAI
page=009 | date=27 Mei 2026 15:49 | title=Polisi menduga ledakan rumah di Malang disebabkan petasan racikan
page=009 | date=26 Mei 2026 22:24 | title=Produsen besek bambu di Kota Malang banjir pesanan jelang Idul Adha
page=009 | date=26 Mei 2026 18:22 | title=Permintaan besek bambu meningkat jelang Idul Adha
page=009 | date=26 Mei 2026 16:50 | title=Pemkot Malang siap buka WTI guna stabilkan harga cabai rawit
page=009 | date=25 Mei 2026 22:55 | title=Polresta Malang Kota buka ruang kritik lewat lomba mural
page=009 | date=25 Mei 2026 22:17 | title=Pengamat: Disinformasi konten AI jadi isu krusial Pemilu 2029
page=009 | date=25 Mei 2026 21:20 | title=Akademisi dorong RI kirim nota protes soal kekerasan relawan GSF
page=010 | date=25 Mei 2026 17:25 | title=Lomba mural Hari Bhayangkara di Malang
page=010 | date=24 Mei 2026 20:32 | title=PSSI Kota Malang: MLSC wadah kembangkan ekosistem sepakbola wanita
page=010 | date=24 Mei 2026 11:07 | title=Polres Malang dalami ledakan petasan di rumah yang tewaskan satu orang
page=010 | date=23 Mei 2026 22:14 | title=Pemkab Malang target bongkar ratoon 7.500 ha dukung swasembada
page=010 | date=21 Mei 2026 22:05 | title=DPR minta pemerintah bantu kembangkan potensi budaya di Malang Raya
page=010 | date=21 Mei 2026 21:53 | title=Komisi X tegaskan RUU Sisdiknas cegah kriminalisasi guru
page=010 | date=21 Mei 2026 21:23 | title=Komisi X: Revisi UU Cagar Budaya kuatkan proses perlindungan
page=010 | date=21 Mei 2026 12:15 | title=Simulasi evakuasi korban kecelakaan
page=010 | date=20 Mei 2026 20:20 | title=Pemkot Malang sebut penerimaan murid baru Sekolah Rakyat tunggu Juknis
page=010 | date=20 Mei 2026 20:17 | title=Polresta Malang Kota tetapkan tersangka kasus asusila
page=011 | date=20 Mei 2026 19:37 | title=Polres Malang layani SIM gratis bagi disabilitas saat Harkitnas
page=011 | date=20 Mei 2026 12:55 | title=Upaya pemberdayaan warga lansia di Malang
page=011 | date=19 Mei 2026 20:07 | title=Semeru kembali simpan kejutan, dua anggrek baru ditemukan
page=011 | date=19 Mei 2026 16:43 | title=Progres pembangunan jembatan perintis garuda
page=011 | date=18 Mei 2026 21:19 | title=DPRD minta Pemkot Malang sertakan data aktual RTH untuk raperda
page=011 | date=18 Mei 2026 16:57 | title=Pengamat usulkan RUU Pemilu perjelas aturan kampanye digital
page=011 | date=18 Mei 2026 12:26 | title=Penguatan literasi dasar siswa PAUD di Kantor Pos
page=011 | date=17 Mei 2026 20:58 | title=Ringankan biaya, Pemkab Pamekasan bantu petani tembakau pupuk non-subsidi
page=011 | date=17 Mei 2026 17:54 | title=Pemkot Malang dorong program RT Berkelas tuntaskan masalah sampah
page=011 | date=16 Mei 2026 21:20 | title=Pemkot Malang dorong inovasi kampung tematik kuatkan daya tarik wisata
page=012 | date=16 Mei 2026 17:00 | title=Wali Kota Malang tak segan pidanakan pelaku pembuangan limbah medis
page=012 | date=15 Mei 2026 18:10 | title=Pemkot Malang antisipasi peredaran daging kurban tak layak konsumsi
page=012 | date=15 Mei 2026 17:56 | title=Pemkot Malang kirim 500 ton sampah guna dukung operasional PSEL
page=012 | date=15 Mei 2026 16:38 | title=Pemkot Malang targetkan 200 UMKM mampu tembus pasar ekspor pada 2026
page=012 | date=14 Mei 2026 21:30 | title=BPS Kota Malang ajak warga transparan sampaikan data di Sensus Ekonomi
page=012 | date=14 Mei 2026 21:00 | title=BPBD Kota Malang minta lurah maksimalkan peta bencana acuan mitigasi
page=012 | date=14 Mei 2026 19:47 | title=BKPSDM Malang belum temukan ASN langgar aturan presensi selama WFH
page=012 | date=14 Mei 2026 19:11 | title=Pemkab Malang percepat penambahan lokasi KNMP
page=012 | date=13 Mei 2026 21:45 | title=KAI: 5.470 penumpang padati Stasiun Malang jelang libur panjang
page=012 | date=13 Mei 2026 20:16 | title=Pemkot Malang siapkan skema tata kelola sampah lewat LSDP
page=013 | date=13 Mei 2026 18:47 | title=Limbah medis berserakan di kawasan perumahan Kota Malang
page=013 | date=12 Mei 2026 21:29 | title=Pemkab Malang optimistis KNMP Pujiharjo tingkatkan tangkapan nelayan
page=013 | date=12 Mei 2026 20:56 | title=Pemkot Malang berdayakan puluhan angkot jadi angkutan pelajar gratis
page=013 | date=12 Mei 2026 20:53 | title=Pemkot Malang buka opsi bentuk Dinas Damkar lewat perombakan OPD
page=013 | date=12 Mei 2026 17:59 | title=Kejari Kota Malang musnahkan 37,8 kg ganja dan 1,47 kg sabu
page=013 | date=12 Mei 2026 11:48 | title=Damkar Kota Malang ungkap pemicu kebakaran ruang praktikum Polinema
page=013 | date=11 Mei 2026 22:45 | title=Pemkot Malang tingkatkan pemantauan cegah kemacetan di libur panjang
page=013 | date=11 Mei 2026 21:45 | title=Pemkot Malang bentuk langkah strategis percepat penanganan sampah
page=013 | date=11 Mei 2026 19:51 | title=Dinkes Kota Malang minta masyarakat terapkan PHBS cegah hantavirus
page=013 | date=11 Mei 2026 19:45 | title=Pemkot Malang perkirakan 11 ribu nakes dan named divaksin campak
page=014 | date=9 Mei 2026 16:00 | title=BRIN apresiasi UMM bertransformasi menjadi "Innovation University"
page=014 | date=8 Mei 2026 19:55 | title=Polisi gagalkan peredaran 8,9 kg ganja dan 1,6 kg sabu di Kota Malang
page=014 | date=8 Mei 2026 19:36 | title=Polres Malang sebut 31 wisatawan pantai Wedi Awu jalani rehabilitas narkoba
page=014 | date=8 Mei 2026 17:47 | title=Polres Malang tetapkan empat tersangka perusakan kendaraan di pantai
page=014 | date=7 Mei 2026 22:35 | title=Kemnaker: Lulusan siap kerja solusi jawab kebutuhan industri
page=014 | date=7 Mei 2026 21:30 | title=UNITRI perluas cakupan kerja sama pemberian beasiswa
page=014 | date=7 Mei 2026 16:13 | title=Penguatan posyandu melalui Integrasi Layanan Primer
page=014 | date=6 Mei 2026 22:32 | title=OJK-PIISEI sasar perempuan di Malang tingkatkan literasi keuangan
page=014 | date=6 Mei 2026 21:50 | title=Pemkot Malang kaji pemanfaatan angkot sebagai "feeder" TransJatim
page=014 | date=6 Mei 2026 16:53 | title=UIN Malang dorong penajaman nalar kritis bentuk aspirasi konstruktif
page=015 | date=6 Mei 2026 15:00 | title=Polres Malang: Tes urine 31 wisatawan Pantai Wedi Awu positif narkoba
page=015 | date=6 Mei 2026 12:29 | title=BI Malang jembatani tradisi dan transaksi dengan Qrisma Fest 2026
page=015 | date=5 Mei 2026 20:55 | title=Pemkot Malang percepat deteksi dini cegah kasus kematian ibu dan bayi
page=015 | date=5 Mei 2026 17:52 | title=Dinas Perdagangan Kota Madiun pastikan pasokan Minyakita aman
page=015 | date=5 Mei 2026 16:54 | title=Polisi selidiki dugaan perusakan kendaraan wisatawan di pantai Malang
page=015 | date=5 Mei 2026 15:40 | title=BPJPH berkomitmen libatkan kampus wujudkan ekosistem halal
page=015 | date=4 Mei 2026 17:50 | title=BRI Malang dorong penyaluran KUR tingkatkan produktivitas UMKM
page=015 | date=4 Mei 2026 16:13 | title=Dinkes Kota Malang imbau masyarakat waspada "heat stroke" saat kemarau
page=015 | date=4 Mei 2026 06:29 | title=Manajemen Arema berjanji lakukan evaluasi guna dongkrak performa tim
page=015 | date=2 Mei 2026 19:46 | title=Pemkab Sampang petakan daerah rawan bencana
page=016 | date=2 Mei 2026 16:15 | title=KAI gandeng Kejari Kota Malang terkait penyelamatan dan pemulihan aset
page=016 | date=1 Mei 2026 17:54 | title=Pemkot Malang minta perusahaan tak asal PHK karyawan
page=016 | date=1 Mei 2026 17:27 | title=Polresta dan Pemkot Malang awasi "daycare" demi keamanan anak
page=016 | date=1 Mei 2026 15:10 | title=Pendakian Gunung Arjuno dan Welirang dibuka 7 Mei 2026
page=016 | date=30 April 2026 21:29 | title=KAI operasikan 12 kereta api dari Stasiun Malang saat libur May Day
page=016 | date=30 April 2026 20:47 | title=Daop 8: Keberangkatan KA di Malang kembali normal pascainsiden Bekasi
page=016 | date=30 April 2026 18:11 | title=Peringatan hari tari sedunia di pusat perbelanjaan
page=016 | date=30 April 2026 16:25 | title=500 personel gabungan disiagakan kawal Hari Buruh di Kota Malang
page=016 | date=29 April 2026 22:25 | title=Anggota DPR RI sebut Bulog Malang serap beras petani secara optimal

     month  count
0  2026-02      4
1  2026-03    112
2  2026-04     96
3  2026-05     85
4  2026-06     69

rows per page:

    page_num  rows                     newest              oldest
0          1    10 2026-06-28 14:16:17.805427 2026-06-25 16:10:00
1          2    10 2026-06-25 13:47:00.000000 2026-06-20 15:08:00
2          3    10 2026-06-20 12:17:00.000000 2026-06-17 21:33:00
3          4    10 2026-06-17 17:42:00.000000 2026-06-13 16:14:00
4          5    10 2026-06-13 11:59:00.000000 2026-06-09 20:01:00
5          6    10 2026-06-09 18:35:00.000000 2026-06-04 16:00:00
6          7    10 2026-06-03 20:17:00.000000 2026-05-31 23:00:00
7          8    10 2026-05-31 21:22:00.000000 2026-05-28 19:10:00
8          9    10 2026-05-28 14:01:00.000000 2026-05-25 21:20:00
9         10    10 2026-05-25 17:25:00.000000 2026-05-20 20:17:00
10        11    10 2026-05-20 19:37:00.000000 2026-05-16 21:20:00
11        12    10 2026-05-16 17:00:00.000000 2026-05-13 20:16:00
12        13    10 2026-05-13 18:47:00.000000 2026-05-11 19:45:00
13        14    10 2026-05-09 16:00:00.000000 2026-05-06 16:53:00
14        15    10 2026-05-06 15:00:00.000000 2026-05-02 19:46:00
15        16    10 2026-05-02 16:15:00.000000 2026-04-29 21:59:00
16        17    10 2026-04-29 21:16:00.000000 2026-04-27 20:55:00
17        18    10 2026-04-27 19:42:00.000000 2026-04-23 22:34:00
18        19    10 2026-04-23 20:45:00.000000 2026-04-21 16:37:00
19        20    10 2026-04-21 16:15:00.000000 2026-04-19 19:56:00
20        21    10 2026-04-18 21:58:00.000000 2026-04-14 16:46:00
21        22    10 2026-04-14 15:27:00.000000 2026-04-11 16:55:00
22        23    10 2026-04-10 20:09:00.000000 2026-04-07 15:19:00
23        24    10 2026-04-06 21:40:00.000000 2026-04-03 20:00:00
24        25    10 2026-04-03 15:40:00.000000 2026-04-01 15:51:00
25        26    10 2026-03-31 16:20:00.000000 2026-03-28 19:44:00
26        27    10 2026-03-28 16:55:00.000000 2026-03-25 16:57:00
27        28    10 2026-03-25 15:49:00.000000 2026-03-20 21:55:00
28        29    10 2026-03-20 19:29:00.000000 2026-03-18 14:31:00
29        30    10 2026-03-18 13:53:00.000000 2026-03-15 22:32:00
30        31    10 2026-03-15 22:05:00.000000 2026-03-14 18:54:00
31        32    10 2026-03-14 16:55:00.000000 2026-03-12 22:35:00
32        33    10 2026-03-12 20:48:00.000000 2026-03-10 14:45:00
33        34    10 2026-03-10 13:50:00.000000 2026-03-07 17:00:00
34        35    10 2026-03-07 06:41:00.000000 2026-03-04 16:39:00
35        36    10 2026-03-03 23:00:00.000000 2026-03-01 10:27:00
36        37     6 2026-03-01 10:25:00.000000 2026-02-28 16:45:00

## Save debug list CSV

In [6]:
df_to_save = live_df if 'live_df' in globals() and len(live_df) else local_df
OUTPUT_PATH.parent.mkdir(exist_ok=True)
df_to_save.to_csv(OUTPUT_PATH, index=False)
print('saved:', OUTPUT_PATH)

saved: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project/csv/antara_jatim_list_debug.csv

## Optional article sample check

In [7]:
sample_rows = (live_df if 'live_df' in globals() and len(live_df) else local_df).head(5)
article_rows = []
for index, row in sample_rows.iterrows():
    try:
        article = scraper.extract_article(row)
        article_rows.append(article)
        print(f"[{len(article_rows)}] content_len={len(article.get('content') or '')} | {short_title(article.get('title'))}")
    except Exception as error:
        print(f"failed sample article {index + 1}: {row.get('url')} | {error}")
article_df = pd.DataFrame(article_rows)
display(article_df[['title', 'published_date', 'content', 'url']].head() if len(article_df) else article_df)

[1] content_len=0 | Liburan di kawasan tiga pantai di Malang
[2] content_len=2147 | PDI Perjuangan Kota Malang dekatkan diri dengan anak muda lewat kompetisi e-sport
[3] content_len=2502 | Menkop siapkan koperasi pesantren jadi pemasok Koperasi Merah Putih
[4] content_len=2247 | Pemkab Malang komunikasikan realisasi hilirisasi garam dengan pusat
[5] content_len=2221 | Ribuan umat Muslim di Malang doakan Prabowo dikuatkan pimpin bangsa

,title,published_date,content,url
0,Liburan di kawasan tiga pantai di Malang,2026-06-28,NaN,https://jatim.antaranews.com/foto/1077469/liburan-di-kawasan-tiga-pantai-di-malang
1,PDI Perjuangan Kota Malang dekatkan diri dengan anak muda lewat kompetisi e-sport,"Pewarta: Ananto Pradana Editor : Astrid Faidlatul Habibah COPYRIGHT © ANTARA 2026 Dilarang keras mengambil konten, melakukan crawling atau pengindeksan otom...","Partai harus mengikuti dinamika di dalam tatanan masyarakat, khususnya ke anak-anak zaman sekarang\nMalang Raya (ANTARA) - Dewan Pimpinan Cabang (DPC) PDI P...",https://jatim.antaranews.com/berita/1077367/pdi-perjuangan-kota-malang-dekatkan-diri-dengan-anak-muda-lewat-kompetisi-e-sport
2,Menkop siapkan koperasi pesantren jadi pemasok Koperasi Merah Putih,"Pewarta: Ananto Pradana Editor : Abdul Hakim COPYRIGHT © ANTARA 2026 Dilarang keras mengambil konten, melakukan crawling atau pengindeksan otomatis untuk AI...","Malang, Jawa Timur (ANTARA) - Menteri Koperasi (Menkop) Ferry Juliantono berkomitmen mengawal perkembangan koperasi pondok pesantren (ponpes) di bawah Majel...",https://jatim.antaranews.com/berita/1077335/menkop-siapkan-koperasi-pesantren-jadi-pemasok-koperasi-merah-putih
3,Pemkab Malang komunikasikan realisasi hilirisasi garam dengan pusat,"Pewarta: Ananto Pradana Editor : Vicki Febrianto COPYRIGHT © ANTARA 2026 Dilarang keras mengambil konten, melakukan crawling atau pengindeksan otomatis untu...","Malang, Jawa Timur (ANTARA) - Pemerintah Kabupaten (Pemkab) Malang, Jawa Timur menyatakan realisasi hilirisasi garam di wilayah pesisir Malang masih dikomun...",https://jatim.antaranews.com/berita/1077292/pemkab-malang-komunikasikan-realisasi-hilirisasi-garam-dengan-pusat
4,Ribuan umat Muslim di Malang doakan Prabowo dikuatkan pimpin bangsa,"Pewarta: Ananto Pradana Editor : Vicki Febrianto COPYRIGHT © ANTARA 2026 Dilarang keras mengambil konten, melakukan crawling atau pengindeksan otomatis untu...","Malang Raya (ANTARA) - Ribuan umat Muslim peserta acara Istighatsah dan Doa Kebangsaan yang diselenggarakan di Pondok Pesantren An Nur 2 Al-Murtadlo, Kabupa...",https://jatim.antaranews.com/berita/1077175/ribuan-umat-muslim-di-malang-doakan-prabowo-dikuatkan-pimpin-bangsa