# Debug List Scraper Malang Times Search
List-only dengan Playwright. URL debug: `https://malangtimes.com/search?keyword=kabupaten+malang`. Tidak scrape artikel detail.

In [12]:
from pathlib import Path
import sys
import importlib
import inspect

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'scrapers').exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
pd.set_option('display.max_colwidth', 180)
pd.set_option('display.max_rows', 200)

from scrapers.common import cutoff_date, fetch_html, fetch_text, parse_date, normalize_date, is_older_than_cutoff, records_to_df

cutoff = cutoff_date()
print('project:', PROJECT_ROOT)
print('cutoff:', cutoff.date())

import scrapers.malangtimes as scraper
scraper = importlib.reload(scraper)
from playwright.async_api import async_playwright
print('module file:', scraper.__file__)

project: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project
cutoff: 2026-02-28
module file: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project/scrapers/malangtimes.py

In [13]:
MAX_PAGES = 200
MAX_CLICKS = 40
TITLE_LIMIT = 90


def short_title(value, limit=TITLE_LIMIT):
    text = '' if pd.isna(value) else str(value).strip()
    return text if len(text) <= limit else text[: limit - 3] + '...'


def ensure_debug_columns(df):
    df = df.copy()
    if 'page_num' not in df.columns:
        df['page_num'] = pd.NA
    if 'published_date' not in df.columns:
        df['published_date'] = None
    df['published_dt'] = df['published_date'].apply(parse_date)
    return df


def print_debug_rows(df):
    for _, row in df.iterrows():
        page = row.get('page_num')
        page_text = '---' if pd.isna(page) else f'{int(page):03d}'
        date_text = row.get('published_date')
        date_text = 'None' if pd.isna(date_text) else str(date_text)
        print(f"page={page_text} | date={date_text} | title={short_title(row.get('title'))}")


def audit_list(df):
    df = ensure_debug_columns(df)
    print('total rows:', len(df))
    if len(df) == 0:
        print('No rows found.')
        return df

    print('first page:', df['page_num'].dropna().min() if df['page_num'].notna().any() else None)
    print('last page:', df['page_num'].dropna().max() if df['page_num'].notna().any() else None)
    print('newest date:', df['published_dt'].max())
    print('oldest date:', df['published_dt'].min())
    print('cutoff date:', cutoff)
    print('reached cutoff:', bool((df['published_dt'].dropna() < cutoff).any()))
    print('null parsed dates:', int(df['published_dt'].isna().sum()))

    print('\nrows per month:')
    display(
        df.assign(month=df['published_dt'].dt.to_period('M').astype(str))
        .groupby('month', dropna=False)
        .size()
        .reset_index(name='count')
    )

    print('\nrows per page:')
    display(
        df.groupby('page_num', dropna=False)
        .agg(
            rows=('url', 'count'),
            newest=('published_dt', 'max'),
            oldest=('published_dt', 'min'),
        )
        .reset_index()
        .tail(60)
    )
    return df

In [14]:
playwright = await async_playwright().start()
browser = await playwright.chromium.launch(headless=True)
page = await browser.new_page()

In [15]:
from bs4 import BeautifulSoup
from datetime import datetime
from dateutil.relativedelta import relativedelta
import re

MALANGTIMES_SEARCH_URL = 'https://malangtimes.com/search?keyword=kabupaten+malang'
RELATIVE_DATE_PATTERN = re.compile(
    r'\b(\d+)\s+(menit|jam|hari|minggu|bulan|tahun)\s+(?:yang\s+)?lalu\b',
    flags=re.IGNORECASE,
)


def parse_relative_date(value, now=None):
    if not value:
        return None

    now = now or datetime.now()
    text = str(value).lower()
    match = RELATIVE_DATE_PATTERN.search(text)

    if not match:
        return None

    amount = int(match.group(1))
    unit = match.group(2)

    if unit == 'menit':
        parsed = now - relativedelta(minutes=amount)
    elif unit == 'jam':
        parsed = now - relativedelta(hours=amount)
    elif unit == 'hari':
        parsed = now - relativedelta(days=amount)
    elif unit == 'minggu':
        parsed = now - relativedelta(weeks=amount)
    elif unit == 'bulan':
        parsed = now - relativedelta(months=amount)
    elif unit == 'tahun':
        parsed = now - relativedelta(years=amount)
    else:
        return None

    return parsed.date().isoformat()


def find_relative_date_text(*values):
    for value in values:
        text = str(value or '').strip()
        match = RELATIVE_DATE_PATTERN.search(text)
        if match:
            return match.group(0).strip()
    return None


def strip_relative_date(value):
    text = str(value or '').strip()
    return RELATIVE_DATE_PATTERN.sub('', text).strip()


def candidate_texts_for_link(link_tag):
    texts = [
        link_tag.get_text(' ', strip=True),
    ]

    title_tag = link_tag.select_one('h3')
    if title_tag:
        texts.append(title_tag.get_text(' ', strip=True))

    current = link_tag
    for _ in range(4):
        current = current.parent
        if not current:
            break
        texts.append(current.get_text(' ', strip=True))

    for sibling in list(link_tag.next_siblings)[:4]:
        if hasattr(sibling, 'get_text'):
            texts.append(sibling.get_text(' ', strip=True))
        else:
            texts.append(str(sibling).strip())

    return texts


async def debug_scrape_search_list(page, max_clicks=MAX_CLICKS):
    rows = []
    seen_urls = set()

    await page.goto(MALANGTIMES_SEARCH_URL, wait_until='networkidle')

    for click_num in range(max_clicks + 1):
        soup = BeautifulSoup(await page.content(), 'html.parser')
        batch_page = click_num + 1

        for link_tag in soup.select("a[href*='/baca/']"):
            url = link_tag.get('href')
            if not url or url in seen_urls:
                continue

            seen_urls.add(url)

            title_tag = link_tag.select_one('h3')
            raw_link_text = link_tag.get_text(' ', strip=True)
            title = title_tag.get_text(' ', strip=True) if title_tag else strip_relative_date(raw_link_text)

            candidate_texts = candidate_texts_for_link(link_tag)
            relative_date = find_relative_date_text(*candidate_texts)
            published_date = parse_relative_date(relative_date)

            rows.append({
                'page_num': batch_page,
                'list_page_url': MALANGTIMES_SEARCH_URL,
                'title': title,
                'url': url,
                'published_date': published_date,
                'relative_date': relative_date,
                'raw_list_text': raw_link_text,
            })

        load_more = page.locator('#load-more')
        if await load_more.count() == 0:
            break

        try:
            await load_more.click(timeout=5000)
            await page.wait_for_timeout(2000)
            print(f'Loaded Malang Times search chunk {batch_page}')
        except Exception as error:
            print(f'Load more stopped: {error}')
            break

    return records_to_df(rows)


list_df = await debug_scrape_search_list(page)
list_df = ensure_debug_columns(list_df)
print_debug_rows(list_df)

print('\nRows with missing relative_date:')
display(
    list_df[list_df['relative_date'].isna()][
        ['page_num', 'title', 'raw_list_text', 'url']
    ].head(20)
)

Loaded Malang Times search chunk 1
Loaded Malang Times search chunk 2
Loaded Malang Times search chunk 3
Loaded Malang Times search chunk 4
Loaded Malang Times search chunk 5
Loaded Malang Times search chunk 6
Loaded Malang Times search chunk 7
Loaded Malang Times search chunk 8
Loaded Malang Times search chunk 9
Loaded Malang Times search chunk 10
Loaded Malang Times search chunk 11
Loaded Malang Times search chunk 12
Loaded Malang Times search chunk 13
Loaded Malang Times search chunk 14
Loaded Malang Times search chunk 15
Loaded Malang Times search chunk 16
Loaded Malang Times search chunk 17
Loaded Malang Times search chunk 18
Loaded Malang Times search chunk 19
Loaded Malang Times search chunk 20
Loaded Malang Times search chunk 21
Loaded Malang Times search chunk 22
Loaded Malang Times search chunk 23
Loaded Malang Times search chunk 24
Loaded Malang Times search chunk 25
Loaded Malang Times search chunk 26
Loaded Malang Times search chunk 27
Loaded Malang Times search chunk 28
Loaded Malang Times search chunk 29
Loaded Malang Times search chunk 30
Loaded Malang Times search chunk 31
Loaded Malang Times search chunk 32
Loaded Malang Times search chunk 33
Loaded Malang Times search chunk 34
Loaded Malang Times search chunk 35
Loaded Malang Times search chunk 36
Loaded Malang Times search chunk 37
Loaded Malang Times search chunk 38
Loaded Malang Times search chunk 39
Loaded Malang Times search chunk 40
Loaded Malang Times search chunk 41
page=001 | date=2026-06-29 | title=Diduga Sudah Setor Puluhan Juta, Pedagang Pasar Buah Karangploso Belum Bisa Tempati Kio...
page=001 | date=2026-06-28 | title=Buka Sarasehan Nasional MPDI, Menkop Ferry Juliantono Dorong Kemandirian Ekonomi Pesant...
page=001 | date=2026-06-28 | title=Viral Nasabah BCA Kepanjen Ngaku Rugi Rp987 Juta, Diduga Kena Modus Deposito Fiktif
page=001 | date=2026-06-27 | title=Pembobol Rumah di Wonosari Diringkus Polisi, Terlacak Dari CCTV Usai Kepergok Curi Motor
page=001 | date=2026-06-26 | title=SDN Kendalpayak Tarik Uang dari Wali Murid secara Mendadak, Berdalih untuk Perbaikan Mu...
page=001 | date=2026-06-26 | title=Atasi Kekeringan di Kabupaten, 7 Desa Dialiri Sumur Bor Polri Presisi
page=001 | date=2026-06-25 | title=Bawa Coban Sewu ke Asia, Kabupaten Malang Bidik Wisman
page=001 | date=None | title=Ramai Pedagang Pisang Ngeluh Rugi Gegara MBG Libur, Netizen Malah Kompak Bersyukur
page=001 | date=None | title=Ramai, Curhatan Nadhif Basalamah Alami Pelecehan Seksual di Media Sosial
page=001 | date=None | title=Disnaker Kota Malang Siapkan Jalur PHI Soal Kisruh RSI Unisma
page=001 | date=None | title=Viral Polemik Siswa Kota Batu Gagal OSN, Dinas Pendidikan Bantah Lalai dan Sebut Berkas...
page=001 | date=None | title=Gempa Pacitan M 5,3 Terasa hingga Yogyakarta, BMKG Ungkap Penyebabnya
page=001 | date=None | title=Korban Latsarmil Kopdes Merah Putih Bertambah: Sudah 5 Nyawa Melayang, Program Masih Be...
page=002 | date=2026-06-24 | title=Bapenda Kabupaten Malang Gencarkan BMW Dekatkan Pelayanan Perpajakan
page=002 | date=2026-06-23 | title=Truk Kontainer Diduga Tergelincir, Tabrak Pembatas Jembatan di Kendalpayak hingga Picu ...
page=002 | date=2026-06-23 | title=KAI Soroti Aktivitas Anak di Rel Kereta Malang, Orang Tua Diimbau Lebih Waspada
page=002 | date=2026-06-22 | title=Lansia di Malang Marak Dilaporkan Hilang Kemudian Ditemukan Tewas
page=002 | date=2026-06-22 | title=Dinas Cipta Karya Sebut Warga Terdampak Pembangunan Perumahan Berhak Dapat Kompensasi
page=002 | date=2026-06-22 | title=Pelaku Curanmor di Masjid Malang Diringkus Polisi: Satu Pelaku Kabur, Motornya Dibakar ...
page=002 | date=2026-06-22 | title=Terjadi 25 Kebakaran di Malang pada Triwulan Pertama 2026, Didominasi Korsleting Listrik
page=003 | date=2026-06-22 | title=Polisi Tangkap 2 Pemuda Pembawa Sajam saat Pengesahan Warga Pencak Silat di Malang
page=003 | date=2026-06-22 | title=Program Bongkar Ratoon Digelar di Malang, Upaya Perkuat Produktivitas Tebu Nasional
page=003 | date=2026-06-22 | title=DPRD Kabupaten Malang Minta Laporan Dugaan Perusakan Bendungan Lahor Dicabut
page=003 | date=2026-06-22 | title=Dinas Perikanan Optimis Kabupaten Malang Dapat Bantuan 100 Lokasi Budidaya Ikan Air Taw...
page=003 | date=2026-06-22 | title=Wabup Lathifah Minta Masyarakat Kabupaten Malang Jaga Warisan Budaya dan Tradisi Leluhur
page=003 | date=2026-06-22 | title=Momentum 1 Muharram 1448 Hijriah, Bupati Sanusi Ajak Masyarakat Perbaiki Diri dan Perer...
page=003 | date=2026-06-22 | title=Bupati Sanusi dan Wabup Lathifah Kompak Sukseskan Sensus Ekonomi 2026 di Kabupaten Malang
page=004 | date=2026-06-22 | title=Oknum Pengasuh Ponpes di Bululawang Jadi Tersangka Dugaan Pelecehan Seksual Terhadap Sa...
page=004 | date=2026-06-22 | title=Riwayat Penyegelan Ponpes di Malang Oleh Yakuza Maneges: Pengasuh Diduga Lecehkan Santr...
page=004 | date=2026-06-15 | title=Pemkab Malang Suntikkan Dana Rp 3,5 Milliar, Targetkan Artha Kanjuruhan Hasilkan Laba d...
page=004 | date=2026-06-15 | title=Pelecehan Seksual Oknum Pengasuh Ponpes Terhadap Santriwati Diduga Berlangsung Puluhan ...
page=004 | date=2026-06-15 | title=Yakuza Maneges Segel 3 Ponpes Usai Pengasuh Diduga Lecehkan Santriwati di Malang, Sempa...
page=004 | date=2026-06-15 | title=Bupati Sanusi Apresiasi Jauhar Muharram Singhasari yang Kolaborasikan Penguatan Spiritu...
page=004 | date=2026-06-15 | title=Dinas Cipta Karya Imbau Warga Lapor Jika Terdampak Pembangunan Perumahan
page=005 | date=2026-06-15 | title=Kepala Dispendik Kabupaten Malang Minta Sekolah Jalankan SE KPK Terkait SPMB
page=005 | date=2026-06-15 | title=DPKPCK Imbau Developer Lengkapi Perizinan, Antisipasi Jalan Rusak Terdampak Truk Pemban...
page=005 | date=2026-06-15 | title=Pemkab Malang Komitmen Sukseskan Pembangunan Pabrik Infus Suryavena dari Muhammadiyah
page=005 | date=2026-06-15 | title=PP Muhammadiyah Bangun Pabrik Infus Suryavena di Kabupaten Malang
page=005 | date=2026-06-15 | title=Pembangunan SPAM Pagak Ditargetkan Selesai Desember 2026, Penuhi Kebutuhan Air Masyarak...
page=005 | date=2026-06-15 | title=Awal Juni 2026 Capaian Pajak 39,11 Persen, Bapenda Kabupaten Malang Masifkan BMW dan Ko...
page=005 | date=2026-06-15 | title=Dispendik Kabupaten Malang Dorong Percepatan Transformasi Digital dan Tetap Imbau ASN J...
page=006 | date=2026-06-08 | title=Polres Malang Libatkan 120 Personel pada Operasi Patuh Semeru 2026, Siap Tindak Pelangg...
page=006 | date=2026-06-08 | title=Tungku Masak Rawan Picu Kebakaran di Kabupaten Malang, Total Kerugian Rp450 Juta
page=006 | date=2026-06-08 | title=Bupati Sanusi Tegaskan Daerah Terpencil di Kabupaten Malang akan Dapatkan Layanan Air M...
page=006 | date=2026-06-08 | title=Lewat DOR di Pakis, Dispendik Kabupaten Malang Larang Sekolah Lakukan Pungutan Liar ke ...
page=006 | date=2026-06-08 | title=Tersangka Penyerangan Wisatawan Surabaya di Pantai Wediawu Malang Dibebaskan: Korban Ca...
page=006 | date=2026-06-08 | title=DPKPCK Tegaskan Bangun Perumahan dan Urus Izin Tak Bisa Bersamaan: Lengkapi Perizinan, ...
page=006 | date=2026-06-08 | title=Cegah Tindakan KKN, Dispendik Kabupaten Malang Perkuat Integritas ASN
page=007 | date=2026-06-08 | title=Pecah Cikal dan Pawai Budaya Buka Hari Jadi Ke-184 Tahun Desa Ngabab Pujon
page=007 | date=2026-06-08 | title=Pelajar 14 Tahun Asal Pakisaji Tewas Tenggelam di Embung Babadan Ngajum
page=007 | date=2026-06-08 | title=Fraksi Gerindra Desak Pemkab Malang Kaji Pembangunan Alun-alun di Kawasan Stadion Kanju...
page=007 | date=2026-06-01 | title=Tungku Kayu Picu Kebakaran Rumah di Kalipare, Korban Alami Kerugian Rp400 Juta
page=007 | date=2026-06-01 | title=Pencuri Uang Kotak Amal di Masjid Lawang Diringkus Polisi
page=007 | date=2026-06-01 | title=Indikasi Developer Perumahan Kena Sanksi Hukum, DPKPCK: Tak Berizin hingga Bangun di Zo...
page=007 | date=2026-06-01 | title=Bupati Sanusi Berikan Atensi Khusus untuk Pembenahan Apotek dan Gudang Obat Puskesmas A...
page=008 | date=2026-05-29 | title=Selang Gas Diduga Bocor saat Masak Daging Picu Kebakaran Rumah di Malang
page=008 | date=2026-05-29 | title=Lansia Ditemukan Tewas di Sumur Diduga Beracun
page=008 | date=2026-05-29 | title=Perumda Jasa Yasa Pindah Loket Pantai Ngliyep Agar Wisatawan Tak Beli Tiket Ganda
page=008 | date=2026-05-29 | title=Pelajar SMP Tewas Terserempet Truk, Setahun 111 Jiwa Melayang Akibat Kecelakaan di Kabu...
page=008 | date=2026-05-29 | title=Ledakan Diduga Petasan di Singosari: Rumah Porak-poranda, 6 Korban Luka-luka
page=008 | date=2026-05-29 | title=Dispendik Kabupaten Malang Sosialisasikan Manajemen Ijazah, Larang Sekolah Tahan Ijazah...
page=008 | date=2026-05-29 | title=Tekan Laka Lantas, Satlantas Polres Malang Rutin Gelar Edukasi, Setahun 793 Kasus Kecel...
page=009 | date=2026-05-29 | title=Dinas Tanaman Pangan Kabupaten Malang Kembangkan Tiga Varietas Padi untuk Sukseskan Ket...
page=009 | date=2026-05-29 | title=DPKPCK Kabupaten Malang Bakal Blacklist Pengembang Perumahan Tak Berizin
page=009 | date=2026-05-29 | title=Ada Perubahan Aturan Izin Perumahan, Berikut Penjelasan Dinas Cipta Karya Agar Tak Jadi...
page=009 | date=2026-05-29 | title=Pemkab Malang Tunggu SK Pelepasan Benih Padi Sukma dari Kementerian Pertanian RI
page=009 | date=2026-05-29 | title=Warga Kepanjen Diduga Tewas Saat Buat Petasan, Hendak Dijual Ketika Iduladha
page=009 | date=2026-05-29 | title=Kuota Bongkar Ratoon 7.500 Hektare di Kabupaten Malang Berpotensi Terpenuhi di 2026
page=009 | date=2026-05-29 | title=Wabup Lathifah Dorong Lulusan Shirothul Fuqoha' Gondanglegi Jadi Contoh Generasi Muda y...
page=010 | date=2026-05-29 | title=Pelaksanaan WFH ASN Diperpanjang, Pemkab Malang Siap Laksanakan dan Komitmen Awasi Kerj...
page=010 | date=2026-05-29 | title=Gelar DOR di SMPN 1 Gondanglegi, Dispendik Gandeng Inspektorat Berikan Pemahaman Pengel...
page=010 | date=2026-05-29 | title=Proyek Pembangunan PSEL Aglomerasi Malang Raya di Kabupaten Malang Terancam Batal
page=010 | date=2026-05-29 | title=Bupati Sanusi Apresiasi Petugas Kebersihan dan Pemulung di TPA Talangagung
page=010 | date=2026-05-29 | title=Seorang Pria Misterius Mengamuk Sambil Bawa Sajam di Sumberpucung
page=010 | date=2026-05-29 | title=Kejari Kabupaten Malang Tangani 62 Perkara Inkrah di Awal Tahun, Didominasi Narkotika d...
page=010 | date=2026-05-29 | title=Akses Jalan Penghubung Malang-Kepanjen Terhambat Pohon Tumbang Setinggi 20 Meter
page=011 | date=2026-05-29 | title=Ratusan Massa Gelar Aksi Damai di DPRD Kabupaten Malang, Tuntut Kejelasan Polemik Porta...
page=011 | date=2026-05-29 | title=Honor Guru PAUD di Kabupaten Malang Tersisa Rp 250 Ribu, Insentif Merosot 50 Persen Ter...
page=011 | date=2026-05-29 | title=Pemkab Malang Bersama TNI Salurkan Bantuan untuk Petani di Kabupaten Malang
page=011 | date=2026-05-29 | title=Puntung Rokok Diduga Picu Kebakaran Pengolahan Limbah Plastik Tajinan
page=011 | date=2026-05-29 | title=Bupati Sanusi Apresiasi Garam Tunnel Sumberoto Donomulyo yang Produksinya Meningkat 8 T...
page=011 | date=2026-05-29 | title=Komplotan Maling Libatkan Residivis Diamankan Polisi Usai Kepergok Curi 53 Kilogram Jeruk
page=011 | date=2026-05-29 | title=Mayat Wanita Lansia Ditemukan Tersangkut di Sungai Gadungan Setelah Hilang 3 Minggu
page=012 | date=2026-05-29 | title=Hasil Pengamatan Hilal Awal Zulhijah 1447 Hijriah: Tak Terlihat di Kabupaten Malang
page=012 | date=2026-05-29 | title=Bupati Sanusi Dorong SPPG di Kabupaten Malang Bisa Jadi Percontohan Nasional
page=012 | date=2026-05-29 | title=Pemkab Malang Percepat Pemberkasan untuk Calon Lokasi KNMP di Kedungsalam Donomulyo
page=012 | date=2026-05-29 | title=Polisi Buru Komplotan Maling Viral, Sehari Sasar 3 Kedai di Malang
page=012 | date=2026-05-29 | title=Daftar Wilayah di Jatim yang Rawan Kebakaran Hutan, Ada Kabupaten Malang
page=012 | date=2026-05-29 | title=Polisi Selidiki Dugaan Pembuangan Bayi di Kawasan Makam Sanggrahan
page=012 | date=2026-05-29 | title=Pertumbuhan Ekonomi Kabupaten Malang Ungguli Nasional, Ini Kata Bupati Sanusi
page=013 | date=2026-05-29 | title=127 Titik KDKMP di Kabupaten Malang Sudah Selesai 100 Persen
page=013 | date=2026-05-29 | title=Dewan Desak Pemkab Malang Telusuri Pembuat Surat Tugas Bermasalah
page=013 | date=2026-05-29 | title=Satgas MBG Kabupaten Malang Segera Bersurat ke BGN untuk Tambahan Kuota SPPG Khusus di ...
page=013 | date=2026-05-29 | title=Bupati Sanusi Dorong Perbaikan Pengelolaan Destinasi Wisata Kabupaten Malang
page=013 | date=2026-05-29 | title=Dinsos Kabupaten Malang Utamakan Anak Putus Sekolah Jadi Casis Sekolah Rakyat, 230 Anak...
page=013 | date=2026-05-29 | title=Hantavirus Tidak Ditemukan di Kabupaten Malang, Dinkes Imbau Masyarakat Jaga Kebersihan...
page=013 | date=2026-05-29 | title=Hasil Rapat Gabungan DPRD: Ditemukan Kesalahan pada Surat Tugas Audiensi Wabup Malang-W...
page=014 | date=2026-05-29 | title=Polisi Sita Belasan Gram Sabu dari Dua Pengedar di Dampit
page=014 | date=2026-05-29 | title=Rapat Pembahasan Dugaan Surat Tugas Palsu Audiensi Wabup Malang-Wapres Gibran Berlangsu...
page=014 | date=2026-05-29 | title=Dinas Cipta Karya Pastikan Tak Beri Izin Pembangunan Perumahan di Lahan Hijau Kabupaten...
page=014 | date=2026-05-29 | title=Lansia Jaringan Pembalakan Hutan Senilai Belasan Juta di Malang Selatan Tertangkap
page=014 | date=2026-05-29 | title=Pemkab Malang Perkuat Program SDIDTK, Upaya Cegah Gangguan Tumbuh Kembang dan Disabilit...
page=014 | date=2026-05-29 | title=Hasil Konfirmasi Polisi Terkait Dugaan Pelecehan Seksual di Sekolah Kepanjen: Keluarga ...
page=014 | date=2026-05-29 | title=DOR Digelar di SMPN 1 Ngantang, Dispensdik Dorong Perangkat Sekolah Wujudkan Public Trust
page=015 | date=2026-05-29 | title=Kandang Ayam di Ngantang Ludes Terbakar,  Kerugian Rp50 Juta
page=015 | date=2026-05-29 | title=Keluarga Terduga Korban Pelecehan Seksual di Sekolah Kepanjen Buat Klarifikasi, Minta V...
page=015 | date=2026-05-29 | title=Sekda Kabupaten Malang Sosialisasikan DBH Pajak Daerah dan Opsen PKB-BBNKB ke Seluruh K...
page=015 | date=2026-05-29 | title=Diduga Rem Blong, Truk Tebu Tabrak Warung hingga Tiang Baliho di Lawang Malang
page=015 | date=2026-05-29 | title=Kunjungi Puskesmas Jabung, Bupati Sanusi Segera Tambah Alat untuk Menunjang Pelayanan d...
page=015 | date=2026-05-29 | title=Viral Dugaan Pelecehan Seksual Siswa SMP di Kepanjen, Korban Menangis Histeris
page=015 | date=2026-05-29 | title=Wabup Lathifah Minta Lulusan SMK di Kabupaten Malang Menjadi Generasi yang Adaptif
page=016 | date=2026-05-29 | title=Kebakaran Gudang di Turen Sebabkan Kerugian Ratusan Juta
page=016 | date=2026-05-29 | title=Sekda Budiar Apresiasi Senam Lansia Yayasan Gerontologi Abiyoso untuk Songsong Hari Lan...
page=016 | date=2026-05-29 | title=Pemkab Malang Gandeng Bank Jatim soal Biaya  Alun-Alun di Kawasan Stadion Kanjuruhan
page=016 | date=2026-05-29 | title=Diskominfo Kabupaten Malang Dorong Provider Bangun BTS di Daerah Blankspot
page=016 | date=2026-05-29 | title=Bapenda Menyapa Warga di Rest Area Madivif 2 Kostrad Singosari Diminati Masyarakat
page=016 | date=2026-05-29 | title=Polisi Tetapkan 4 Tersangka Dugaan Anarkisme Kepada Wisatawan Asal Surabaya di Pantai W...
page=016 | date=2026-05-29 | title=Bupati Sanusi Berencana Perluas Area Puskesmas Kepanjen untuk Tingkatkan Kenyamanan
page=017 | date=2026-05-29 | title=Sekda Budiar Dorong DWP Lakukan Penguatan Pemberdayaan Perempuan di Masing-masing Peran...
page=017 | date=2026-05-29 | title=Kepala Bapenda Turun Gunung Pimpin BMW di Desa Purwodadi Donomulyo Malang
page=017 | date=2026-05-29 | title=Fasilitas Alun-alun di Kawasan Stadion Kanjuruhan: Rest Area hingga Gerai UMKM, Anggara...
page=017 | date=2026-05-29 | title=Awal Mei 2026 Capaian Pajak Reklame dan PBB Masih Rendah, Bapenda Kabupaten Malang Masi...
page=017 | date=2026-05-29 | title=Kekurangan Sarpras, Dinkes Kabupaten Malang Buka Suara Perihal Kondisi RSUD Ngantang
page=017 | date=2026-05-29 | title=Pemkab Malang Siap Sukseskan Sensus Ekonomi 2026, Gali Data Akurat demi Kebijakan Tepat
page=017 | date=2026-05-29 | title=Wakil Kepala BPS RI Ajak Seluruh Stakeholder Sukseskan Sensus Ekonomi 2026 di Malang Raya
page=018 | date=2026-05-29 | title=Kabupaten Malang Raih Tiga Penghargaan di Indonesia Halal Ecosystem Summit dan UB Halal...
page=018 | date=2026-05-29 | title=Komplotan Pengedar Narkotika di Dampit Diringkus, Polisi Sita 12 Paket Sabu Siap Edar
page=018 | date=2026-05-29 | title=Polisi Temukan Botol Miras pada Insiden Dugaan Perusakan 6 Kendaraan Wisatawan Asal Sur...
page=018 | date=2026-05-29 | title=Viral Wisatawan Asal Surabaya Diduga Diserang di Vila Wediawu Malang
page=018 | date=2026-05-29 | title=Dispendik Kabupaten Malang Imbau Kepala Sekolah Bina ASN: Jangan Biarkan Melenceng!
page=018 | date=2026-05-29 | title=Polisi Buru Komplotan Curanmor Viral di Masjid Gondanglegi, Beraksi Saat Salat Berjamaah
page=018 | date=2026-05-29 | title=Fraksi PDI Perjuangan Bersiap Ajukan Hak Interpelasi: Usut Dugaan Surat Tugas Palsu Aud...
page=019 | date=2026-05-29 | title=Sekda Kabupaten Malang Buka Sosialisasi DASHAT, Wujudkan Dapur Sehat Atasi Stunting
page=019 | date=2026-05-29 | title=Kabupaten Malang Bakal Ada Wisata Jetski, Uji Coba Sudah Dimulai
page=019 | date=2026-05-29 | title=Lomba Kicau Gantangan Wijaya Kusuma Diserbu Ratusan Peserta Berbagai Kota, Dongkrak Eko...
page=019 | date=2026-05-29 | title=Polisi Selidiki Curanmor Viral di Singosari, Pelaku Diduga Gunakan Oli dan Air Keras Sa...
page=019 | date=2026-05-29 | title=Sempat Hilang Saat Cari Ikan Pakai Alat Setrum, Lansia Asal Ngajum Ditemukan Tewas di S...
page=019 | date=2026-05-29 | title=Grand Opening Gantangan Wijaya Kusuma Hadirkan Lomba Burung, Jadi Ajang Silaturahmi Kic...
page=019 | date=2026-05-29 | title=Ratusan Kicau Mania Antusias Perebutkan Piala Disparbud Kabupaten Malang di Gantangan W...
page=020 | date=2026-05-29 | title=Pohon Tumbang Rusak Rumah Lansia di Malang, Sebabkan Kerugian hingga Puluhan Juta
page=020 | date=2026-05-29 | title=Patuhi Instruksi Bupati Sanusi, Dinas Perikanan Siapkan Bibit Ikan untuk Ketahanan Pang...
page=020 | date=2026-05-29 | title=Bupati Sanusi Komitmen Kembangkan Program Ketahanan Pangan di Sekolah-Sekolah Kabupaten...
page=020 | date=2026-05-29 | title=Diskominfo Kabupaten Malang Terima Laporan Keluhan Menu MBG
page=020 | date=2026-05-29 | title=DPUBM Kabupaten Malang: Sepanjang Jalan Gondanglegi-Balekambang Dipasangi Lampu Solar C...
page=020 | date=2026-05-29 | title=Pemkab Malang Dapat Jatah 32 Ribu Dosis Vaksin PMK untuk Ternak Warga, Distribusi Sudah...
page=020 | date=2026-05-29 | title=Orang Tua Paksa Balita Ngamen di Stadion Kanjuruhan, Diduga Eksploitasi Anak sejak Bayi
page=021 | date=2026-05-29 | title=DPRD Kabupaten Malang Segera Gelar Raker Bahas Proyek Tomoland yang Diduga Belum Berizin
page=021 | date=2026-05-29 | title=Cuaca Ekstrem Melanda 2 Desa di Malang, Sejumlah Rumah Rusak Diterjang Angin Kencang
page=021 | date=2026-05-29 | title=Usai Temui Kepala BKN RI, Bupati Sanusi Tegaskan Penempatan ASN Tidak Melihat Usia Teta...
page=021 | date=2026-05-29 | title=Hujan Disertai Angin Kencang Rusak Rumah hingga Fasilitas Sosial di Jabung
page=021 | date=2026-05-29 | title=Pembangunan Gedung Baru Puskesmas Bululawang Tahap Dua akan Dilakukan Tahun Depan
page=021 | date=2026-05-29 | title=Pemkab Malang Harap KKP RI dapat Segera Penuhi Kelengkapan Kebutuhan di KNMP Pujiharjo
page=021 | date=2026-04-29 | title=Prevalensi Stunting Kabupaten Malang Turun Menjadi 5,85 Persen, Dinkes Terus Percepat P...
page=022 | date=2026-04-29 | title=Proyek Tomoland di Kabupaten Malang Disorot, Desa Klaim Tak Pernah Terima Pengajuan Izin
page=022 | date=2026-04-29 | title=DLH Kabupaten Malang Peringatkan SPPG Terkait Pengelolaan Limbah Dapur MBG: Wajib Milik...
page=022 | date=2026-04-29 | title=Kapasitas Lima Puskesmas dan Satu RSUD di Kabupaten Malang Segera Ditingkatkan

,page_num,title,raw_list_text,url
7,1,"Ramai Pedagang Pisang Ngeluh Rugi Gegara MBG Libur, Netizen Malah Kompak Bersyukur","2 Ramai Pedagang Pisang Ngeluh Rugi Gegara MBG Libur, Netizen Malah Kompak Bersyukur",https://malangtimes.com/baca/3331346156/20260628/063300/ramai-pedagang-pisang-ngeluh-rugi-gegara-mbg-libur-netizen-malah-kompak-bersyukur
8,1,"Ramai, Curhatan Nadhif Basalamah Alami Pelecehan Seksual di Media Sosial","3 Ramai, Curhatan Nadhif Basalamah Alami Pelecehan Seksual di Media Sosial",https://malangtimes.com/baca/3331346149/20260628/052700/ramai-curhatan-nadhif-basalamah-alami-pelecehan-seksual-di-media-sosial
9,1,Disnaker Kota Malang Siapkan Jalur PHI Soal Kisruh RSI Unisma,4 Disnaker Kota Malang Siapkan Jalur PHI Soal Kisruh RSI Unisma,https://malangtimes.com/baca/3331346147/20260628/043500/disnaker-kota-malang-siapkan-jalur-phi-soal-kisruh-rsi-unisma
10,1,"Viral Polemik Siswa Kota Batu Gagal OSN, Dinas Pendidikan Bantah Lalai dan Sebut Berkas Sudah Lengkap","5 Viral Polemik Siswa Kota Batu Gagal OSN, Dinas Pendidikan Bantah Lalai dan Sebut Berkas Sudah Lengkap",https://malangtimes.com/baca/3331346132/20260628/125700/viral-polemik-siswa-kota-batu-gagal-osn-dinas-pendidikan-bantah-lalai-dan-sebut-berkas-sudah-lengkap
11,1,"Gempa Pacitan M 5,3 Terasa hingga Yogyakarta, BMKG Ungkap Penyebabnya","6 Gempa Pacitan M 5,3 Terasa hingga Yogyakarta, BMKG Ungkap Penyebabnya",https://malangtimes.com/baca/3331346100/20260627/064000/gempa-pacitan-m-5-3-terasa-hingga-yogyakarta-bmkg-ungkap-penyebabnya
12,1,"Korban Latsarmil Kopdes Merah Putih Bertambah: Sudah 5 Nyawa Melayang, Program Masih Berlanjut?","7 Korban Latsarmil Kopdes Merah Putih Bertambah: Sudah 5 Nyawa Melayang, Program Masih Berlanjut?",https://malangtimes.com/baca/3331346081/20260627/012900/korban-latsarmil-kopdes-merah-putih-bertambah-sudah-5-nyawa-melayang-program-masih-berlanjut

In [16]:
list_df = audit_list(list_df)

total rows: 293
first page: 1
last page: 41
newest date: 2026-06-29 00:00:00
oldest date: 2026-03-29 00:00:00
cutoff date: 2026-02-28 09:20:36.028530
reached cutoff: False
null parsed dates: 6

rows per month:

     month  count
0  2026-03     23
1  2026-04    118
2  2026-05     97
3  2026-06     49
4      NaN      6

rows per page:

    page_num  rows     newest     oldest
0          1    13 2026-06-29 2026-06-25
1          2     7 2026-06-24 2026-06-22
2          3     7 2026-06-22 2026-06-22
3          4     7 2026-06-22 2026-06-15
4          5     7 2026-06-15 2026-06-15
5          6     7 2026-06-08 2026-06-08
6          7     7 2026-06-08 2026-06-01
7          8     7 2026-05-29 2026-05-29
8          9     7 2026-05-29 2026-05-29
9         10     7 2026-05-29 2026-05-29
10        11     7 2026-05-29 2026-05-29
11        12     7 2026-05-29 2026-05-29
12        13     7 2026-05-29 2026-05-29
13        14     7 2026-05-29 2026-05-29
14        15     7 2026-05-29 2026-05-29
15        16     7 2026-05-29 2026-05-29
16        17     7 2026-05-29 2026-05-29
17        18     7 2026-05-29 2026-05-29
18        19     7 2026-05-29 2026-05-29
19        20     7 2026-05-29 2026-05-29
20        21     7 2026-05-29 2026-04-29
21        22     7 2026-04-29 2026-04-29
22        23     7 2026-04-29 2026-04-29
23        24     7 2026-04-29 2026-04-29
24        25     7 2026-04-29 2026-04-29
25        26     7 2026-04-29 2026-04-29
26        27     7 2026-04-29 2026-04-29
27        28     7 2026-04-29 2026-04-29
28        29     7 2026-04-29 2026-04-29
29        30     7 2026-04-29 2026-04-29
30        31     7 2026-04-29 2026-04-29
31        32     7 2026-04-29 2026-04-29
32        33     7 2026-04-29 2026-04-29
33        34     7 2026-04-29 2026-04-29
34        35     7 2026-04-29 2026-04-29
35        36     7 2026-04-29 2026-04-29
36        37     7 2026-04-29 2026-04-29
37        38     7 2026-04-29 2026-03-29
38        39     7 2026-03-29 2026-03-29
39        40     7 2026-03-29 2026-03-29
40        41     7 2026-03-29 2026-03-29

In [17]:
await browser.close()
await playwright.stop()

In [18]:
output_path = PROJECT_ROOT / 'csv' / 'malangtimes_list_debug.csv'
list_df.to_csv(output_path, index=False)
output_path

PosixPath('/Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project/csv/malangtimes_list_debug.csv')

## Optional article sample check

Ambil beberapa artikel detail, cek `content`, lalu simpan ke article debug CSV.

In [ ]:

ARTICLE_SAMPLE_SIZE = 5
ARTICLE_DEBUG_OUTPUT_PATH = PROJECT_ROOT / 'csv' / 'malangtimes_article_debug.csv'

article_rows = []
sample_rows = list_df[list_df['published_date'].notna()].head(ARTICLE_SAMPLE_SIZE)
for index, row in sample_rows.iterrows():
    try:
        article = await scraper.extract_article(page, row)
        article_rows.append(article)
        print(f"[{len(article_rows)}] content_len={len(article.get('content') or '')} | {short_title(article.get('title'))}")
    except Exception as error:
        print(f"failed sample article {index + 1}: {row.get('url')} | {error}")

article_df = pd.DataFrame(article_rows)
ARTICLE_DEBUG_OUTPUT_PATH.parent.mkdir(exist_ok=True)
article_df.to_csv(ARTICLE_DEBUG_OUTPUT_PATH, index=False)
print('saved:', ARTICLE_DEBUG_OUTPUT_PATH)
display(article_df[['title', 'published_date', 'content', 'url']].head() if len(article_df) else article_df)