# Debug Scraper Memox

Local HTML first, then optional live list/article checks. Output list CSV: `csv/memox_list_debug.csv`.

In [1]:
from pathlib import Path
import sys
import importlib
from urllib.parse import urljoin

import pandas as pd
from bs4 import BeautifulSoup

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'scrapers').exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scrapers.common import cutoff_date, parse_date, records_to_df
import scrapers.memox as scraper
scraper = importlib.reload(scraper)

pd.set_option('display.max_rows', 200)
pd.set_option('display.max_colwidth', 160)

SAMPLE_PATH = PROJECT_ROOT / 'html_samples/memox.html'
OUTPUT_PATH = PROJECT_ROOT / 'csv/memox_list_debug.csv'
MAX_PAGES = 200
TITLE_LIMIT = 90
cutoff = cutoff_date()

print('project:', PROJECT_ROOT)
print('module:', scraper.__file__)
print('sample:', SAMPLE_PATH)
print('cutoff:', cutoff.date())

project: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project
module: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project/scrapers/memox.py
sample: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project/html_samples/memox.html
cutoff: 2026-02-28

In [2]:

def short_title(value, limit=TITLE_LIMIT):
    text = '' if pd.isna(value) else str(value).strip()
    return text if len(text) <= limit else text[: limit - 3] + '...'


def ensure_debug_columns(df):
    df = df.copy()
    if 'page_num' not in df.columns:
        df['page_num'] = pd.NA
    if 'published_date' not in df.columns:
        df['published_date'] = None
    df['published_dt'] = df['published_date'].apply(parse_date)
    return df


def print_debug_rows(df):
    for _, row in df.iterrows():
        page = row.get('page_num')
        page_text = '---' if pd.isna(page) else f'{int(page):03d}'
        date_text = row.get('published_date')
        date_text = 'None' if pd.isna(date_text) else str(date_text)
        print(f"page={page_text} | date={date_text} | title={short_title(row.get('title'))}")


def audit_list(df):
    df = ensure_debug_columns(df)
    print('total rows:', len(df))
    if len(df) == 0:
        print('No rows found.')
        return df
    print('first page:', df['page_num'].dropna().min() if df['page_num'].notna().any() else None)
    print('last page:', df['page_num'].dropna().max() if df['page_num'].notna().any() else None)
    print('newest date:', df['published_dt'].max())
    print('oldest date:', df['published_dt'].min())
    print('cutoff date:', cutoff)
    print('reached cutoff:', bool((df['published_dt'].dropna() < cutoff).any()))
    print('null parsed dates:', int(df['published_dt'].isna().sum()))

    print('\nrows per month:')
    display(
        df.assign(month=df['published_dt'].dt.to_period('M').astype(str))
        .groupby('month', dropna=False)
        .size()
        .reset_index(name='count')
    )

    print('\nrows per page:')
    display(
        df.groupby('page_num', dropna=False)
        .agg(rows=('url', 'count'), newest=('published_dt', 'max'), oldest=('published_dt', 'min'))
        .reset_index()
        .tail(80)
    )
    return df

In [3]:

def parse_local_list(html_text):
    soup = BeautifulSoup(html_text, 'html.parser')
    rows = []
    for card in soup.select('article'):
        title_tag = card.select_one('h2.entry-title a[href], h3 a[href]')
        link_tag = title_tag or card.select_one('a.post-thumbnail[href]')
        date_tag = card.select_one('time.entry-date.published, time.entry-date')
        excerpt_tag = card.select_one('.entry-content, .entry-summary')
        image_tag = card.select_one('img')
        if not title_tag or not link_tag:
            continue
        rows.append({
            'page_num': 1,
            'list_page_url': scraper.BASE_URL,
            'title': title_tag.get_text(' ', strip=True),
            'url': urljoin(scraper.BASE_URL, link_tag['href']),
            'published_date': (date_tag.get('datetime') or date_tag.get_text(' ', strip=True)) if date_tag else None,
            'excerpt': excerpt_tag.get_text(' ', strip=True) if excerpt_tag else None,
            'image_url': (image_tag.get('data-src') or image_tag.get('src')) if image_tag else None,
        })
    return records_to_df(rows)

## Local HTML list parse

In [4]:
html_text = SAMPLE_PATH.read_text(errors='replace')
local_df = parse_local_list(html_text)
local_df = ensure_debug_columns(local_df)
print_debug_rows(local_df)
local_df = audit_list(local_df)

page=001 | date=2026-06-26T13:15:52+07:00 | title=Usai Diresmikan Kapolres Malang Ratusan Jamaah Sholat Jumat Datangi Masjid Budi Trianti...
page=001 | date=2026-06-25T15:51:59+07:00 | title=Sambut Hari Bhayangkara ke-80 Polres Malang Bangun 7 Sumur Bor di 3 Kecamatan
page=001 | date=2026-06-24T21:01:54+07:00 | title=Giat Donor Darah Hari Bhayangkara ke-80 di Polres Malang Diikuti TNI dan Masyarakat Umum
page=001 | date=2026-06-24T20:52:40+07:00 | title=Mengaku Ajudan Gubenur Jatim, 2 Tersangka Kasus Penipuan Program UMKM Diamankan Polres ...
page=001 | date=2026-06-23T12:06:27+07:00 | title=Jelang Hari Bhayangkara ke-80, Kapolres Malang Pimpin Giat Ziarah dan Tabur Bunga di TMP
page=001 | date=2026-06-20T21:56:16+07:00 | title=Polres Malang Jaring Atlet Esport Lewat Turnamen Mobile Legends Kapolres Malang Cup 2026
page=001 | date=2026-06-19T20:00:16+07:00 | title=Jajaran Polsek Polres Malang Ramaikan Kapolres Malang Cup Jelang Hari Bhayangkara ke-80
page=001 | date=2026-06-19T19:57:15+07:00 | title=Sambut Hari Bhayangkara ke-80, Polres Malang Bersih-Bersih Vihara di Lawang
page=001 | date=2026-06-19T19:53:27+07:00 | title=Terpergok Saat Curi Sepeda Motor Jamaah Masjid Pria Asal Jabung Diamankan Polisi
page=001 | date=2026-06-19T10:14:25+07:00 | title=Tim Sepak Bola Polres Malang Gulung Tim Jurnalis Pos Malang Skor 4-3
page=001 | date=2026-06-18T14:21:21+07:00 | title=Polres Malang Amankan Dua Pemuda Membawa Sajam Saat Ingin Merayakan Pengesahan Warga Ba...
page=001 | date=2026-06-18T12:00:51+07:00 | title=Taruna Akpol Tingkat III/58 Blusukan ke Samsat Talangagung Pelajari Proses Administrasi...
page=001 | date=2026-06-15T19:59:13+07:00 | title=Posyandu di Alfamart Tunjungtirto Malang Disambut Antusias Ibu hamil, Balita dan Lansia
page=001 | date=2026-06-15T14:07:08+07:00 | title=Sespripim Polda Jatim Kompol Fahmi Jabat Wakapolres Malang
page=001 | date=2026-06-14T20:21:29+07:00 | title=Dua Sopir Distribusi Gudang Resto Ocean Garden Diamankan Satreskrim Polres Malang
page=001 | date=2026-06-14T13:10:26+07:00 | title=Pengasuh Ponpes Nurul Izzah Bululawang Diiringi ke Polres Malang Dalam Kasus Dugaan Pen...
page=001 | date=2026-06-12T21:53:32+07:00 | title=Kini Ruang Proses BAP di Polres Malang Terekam Audio Visual
page=001 | date=2026-06-12T21:43:15+07:00 | title=Sambut Hari Bhayangkara ke-80 Pengurus Bhayangkari Cabang Malang Doa Bersama Anak Yatim
page=001 | date=2026-06-11T19:16:47+07:00 | title=Putra Ferdy Sambo Jalani Latja di Polres Malang Bersama 15 Taruna Akpol Tingkat III/58 ...
page=001 | date=2026-06-10T16:28:23+07:00 | title=Kabar Gembira Polres Malang Tetapkan Gus Idris Tersangka Kasus Kekerasan Seksual
page=001 | date=2026-06-06T17:38:02+07:00 | title=Perempuan di Singosari Diamankan Polisi Akibat Hutang Pengambilan Barang
page=001 | date=2026-06-06T17:35:16+07:00 | title=Pendaki Semeru Jalur Ilegal yang Terperosok di Jurang Dievakuasi Tim Gabungan
page=001 | date=2026-06-05T16:26:49+07:00 | title=Sambut Hari Bhayangkara ke-80 Tahun 2026, Polres Malang Bersihkan Pura Kendalisodo
page=001 | date=2026-06-05T10:00:20+07:00 | title=Tingkatkan Produktivitas Budidaya Ikan Lele, BRI Branch Office Kepanjen Bantu 10 Kolam ...
page=001 | date=2026-06-04T19:31:40+07:00 | title=Pemprov Jatim Nobatkan SDN 1 Sidodadi Gedangan Juara Favorit 3 Lomba Moderasi Beragama
page=001 | date=2026-06-03T12:33:11+07:00 | title=Lapas Malang Amankan Vitamin C yang Diseludupkan Lewat Pembalut
page=001 | date=2026-06-03T12:29:31+07:00 | title=Kasat lantas Polres Batu AKP Kevin Kini Jabat Kapolsek Dampit Polres Malang
page=001 | date=2026-06-02T18:20:16+07:00 | title=Kasus Pengeroyokan di Pantai Wediawu Berakhir Damai Pelapor Cabut Laporan
page=001 | date=2026-06-02T17:18:34+07:00 | title=Kisah Ni’amah, Nasabah KUR BRI di Kepanjen yang Sukses Menjadi Agen Toko Sembako dan To...
page=001 | date=2026-06-02T10:25:58+07:00 | title=Hitungan Jam, Dua Pelaku Curanmor Dibekuk URC Satreskrim Polres Malang
page=001 | date=2026-06-02T09:19:35+07:00 | title=BRI Kepanjen Serahkan Bantuan Laptop kepada Kodim 0818 Malang-Batu
page=001 | date=2026-05-31T20:32:45+07:00 | title=Permudah Akses Layanan Keuangan, AgenBRILink BRI Blusukan ke Wilayah Malang Selatan
page=001 | date=2026-05-27T18:39:27+07:00 | title=Ribuan Warga Binaan Menyantap Menu Gulai Hewan Kurban di Lapas Kelas I Malang
page=001 | date=2026-05-27T18:11:39+07:00 | title=Usai Solat Idul Adha Polres Malang Salurkan 22 Ekor Sapi dan 73 Ekor Kambing Kurban ke ...
page=001 | date=2026-05-26T20:39:13+07:00 | title=Ledakan Rumah Diduga Berasal dari Racikan Petasan Diselidiki Polres Malang
page=001 | date=2026-05-26T20:36:41+07:00 | title=Polres Malang Kerahkan Ratusan Personel Amankan Malam Takbir Idul Adha 1447 H
total rows: 36
first page: 1
last page: 1
newest date: 2026-06-26 13:15:52
oldest date: 2026-05-26 20:36:41
cutoff date: 2026-02-28 12:19:25.879283
reached cutoff: False
null parsed dates: 0

rows per month:

     month  count
0  2026-05      5
1  2026-06     31

rows per page:

   page_num  rows              newest              oldest
0         1    36 2026-06-26 13:15:52 2026-05-26 20:36:41

## Live list scrape

In [5]:
live_df = scraper.scrape_list(cutoff, max_pages=MAX_PAGES)
live_df = ensure_debug_columns(live_df)
print_debug_rows(live_df)
live_df = audit_list(live_df)

Scraping Memox page 1: https://memox.co.id/tag/kabupaten-malang/
Scraping Memox page 2: https://memox.co.id/tag/kabupaten-malang/page/2/
Scraping Memox page 3: https://memox.co.id/tag/kabupaten-malang/page/3/
Scraping Memox page 4: https://memox.co.id/tag/kabupaten-malang/page/4/
Scraping Memox page 5: https://memox.co.id/tag/kabupaten-malang/page/5/
Scraping Memox page 6: https://memox.co.id/tag/kabupaten-malang/page/6/
Scraping Memox page 7: https://memox.co.id/tag/kabupaten-malang/page/7/
Scraping Memox page 8: https://memox.co.id/tag/kabupaten-malang/page/8/
Scraping Memox page 9: https://memox.co.id/tag/kabupaten-malang/page/9/
Scraping Memox page 10: https://memox.co.id/tag/kabupaten-malang/page/10/
Scraping Memox page 11: https://memox.co.id/tag/kabupaten-malang/page/11/
Scraping Memox page 12: https://memox.co.id/tag/kabupaten-malang/page/12/
page=001 | date=2026-06-26T13:15:52+07:00 | title=Usai Diresmikan Kapolres Malang Ratusan Jamaah Sholat Jumat Datangi Masjid Budi Trianti...
page=001 | date=2026-06-25T15:51:59+07:00 | title=Sambut Hari Bhayangkara ke-80 Polres Malang Bangun 7 Sumur Bor di 3 Kecamatan
page=001 | date=2026-06-24T21:01:54+07:00 | title=Giat Donor Darah Hari Bhayangkara ke-80 di Polres Malang Diikuti TNI dan Masyarakat Umum
page=001 | date=2026-06-24T20:52:40+07:00 | title=Mengaku Ajudan Gubenur Jatim, 2 Tersangka Kasus Penipuan Program UMKM Diamankan Polres ...
page=001 | date=2026-06-23T12:06:27+07:00 | title=Jelang Hari Bhayangkara ke-80, Kapolres Malang Pimpin Giat Ziarah dan Tabur Bunga di TMP
page=001 | date=2026-06-20T21:56:16+07:00 | title=Polres Malang Jaring Atlet Esport Lewat Turnamen Mobile Legends Kapolres Malang Cup 2026
page=001 | date=2026-06-19T20:00:16+07:00 | title=Jajaran Polsek Polres Malang Ramaikan Kapolres Malang Cup Jelang Hari Bhayangkara ke-80
page=001 | date=2026-06-19T19:57:15+07:00 | title=Sambut Hari Bhayangkara ke-80, Polres Malang Bersih-Bersih Vihara di Lawang
page=001 | date=2026-06-19T19:53:27+07:00 | title=Terpergok Saat Curi Sepeda Motor Jamaah Masjid Pria Asal Jabung Diamankan Polisi
page=001 | date=2026-06-19T10:14:25+07:00 | title=Tim Sepak Bola Polres Malang Gulung Tim Jurnalis Pos Malang Skor 4-3
page=002 | date=2026-06-18T14:21:21+07:00 | title=Polres Malang Amankan Dua Pemuda Membawa Sajam Saat Ingin Merayakan Pengesahan Warga Ba...
page=002 | date=2026-06-18T12:00:51+07:00 | title=Taruna Akpol Tingkat III/58 Blusukan ke Samsat Talangagung Pelajari Proses Administrasi...
page=002 | date=2026-06-15T19:59:13+07:00 | title=Posyandu di Alfamart Tunjungtirto Malang Disambut Antusias Ibu hamil, Balita dan Lansia
page=002 | date=2026-06-15T14:07:08+07:00 | title=Sespripim Polda Jatim Kompol Fahmi Jabat Wakapolres Malang
page=002 | date=2026-06-14T20:21:29+07:00 | title=Dua Sopir Distribusi Gudang Resto Ocean Garden Diamankan Satreskrim Polres Malang
page=002 | date=2026-06-14T13:10:26+07:00 | title=Pengasuh Ponpes Nurul Izzah Bululawang Diiringi ke Polres Malang Dalam Kasus Dugaan Pen...
page=002 | date=2026-06-12T21:53:32+07:00 | title=Kini Ruang Proses BAP di Polres Malang Terekam Audio Visual
page=002 | date=2026-06-12T21:43:15+07:00 | title=Sambut Hari Bhayangkara ke-80 Pengurus Bhayangkari Cabang Malang Doa Bersama Anak Yatim
page=002 | date=2026-06-11T19:16:47+07:00 | title=Putra Ferdy Sambo Jalani Latja di Polres Malang Bersama 15 Taruna Akpol Tingkat III/58 ...
page=002 | date=2026-06-10T16:28:23+07:00 | title=Kabar Gembira Polres Malang Tetapkan Gus Idris Tersangka Kasus Kekerasan Seksual
page=002 | date=2026-06-06T17:38:02+07:00 | title=Perempuan di Singosari Diamankan Polisi Akibat Hutang Pengambilan Barang
page=002 | date=2026-06-06T17:35:16+07:00 | title=Pendaki Semeru Jalur Ilegal yang Terperosok di Jurang Dievakuasi Tim Gabungan
page=002 | date=2026-06-05T16:26:49+07:00 | title=Sambut Hari Bhayangkara ke-80 Tahun 2026, Polres Malang Bersihkan Pura Kendalisodo
page=003 | date=2026-06-05T10:00:20+07:00 | title=Tingkatkan Produktivitas Budidaya Ikan Lele, BRI Branch Office Kepanjen Bantu 10 Kolam ...
page=003 | date=2026-06-04T19:31:40+07:00 | title=Pemprov Jatim Nobatkan SDN 1 Sidodadi Gedangan Juara Favorit 3 Lomba Moderasi Beragama
page=003 | date=2026-06-03T12:33:11+07:00 | title=Lapas Malang Amankan Vitamin C yang Diseludupkan Lewat Pembalut
page=003 | date=2026-06-03T12:29:31+07:00 | title=Kasat lantas Polres Batu AKP Kevin Kini Jabat Kapolsek Dampit Polres Malang
page=003 | date=2026-06-02T18:20:16+07:00 | title=Kasus Pengeroyokan di Pantai Wediawu Berakhir Damai Pelapor Cabut Laporan
page=003 | date=2026-06-02T17:18:34+07:00 | title=Kisah Ni’amah, Nasabah KUR BRI di Kepanjen yang Sukses Menjadi Agen Toko Sembako dan To...
page=003 | date=2026-06-02T10:25:58+07:00 | title=Hitungan Jam, Dua Pelaku Curanmor Dibekuk URC Satreskrim Polres Malang
page=003 | date=2026-06-02T09:19:35+07:00 | title=BRI Kepanjen Serahkan Bantuan Laptop kepada Kodim 0818 Malang-Batu
page=003 | date=2026-05-31T20:32:45+07:00 | title=Permudah Akses Layanan Keuangan, AgenBRILink BRI Blusukan ke Wilayah Malang Selatan
page=003 | date=2026-05-27T18:39:27+07:00 | title=Ribuan Warga Binaan Menyantap Menu Gulai Hewan Kurban di Lapas Kelas I Malang
page=003 | date=2026-05-27T18:11:39+07:00 | title=Usai Solat Idul Adha Polres Malang Salurkan 22 Ekor Sapi dan 73 Ekor Kambing Kurban ke ...
page=003 | date=2026-05-26T20:39:13+07:00 | title=Ledakan Rumah Diduga Berasal dari Racikan Petasan Diselidiki Polres Malang
page=003 | date=2026-05-26T20:36:41+07:00 | title=Polres Malang Kerahkan Ratusan Personel Amankan Malam Takbir Idul Adha 1447 H
page=004 | date=2026-05-26T20:27:45+07:00 | title=Perkuat Sinergi Polres Malang Rakor Korwas PPNS dan Implementasi KUHAP
page=004 | date=2026-05-25T15:23:16+07:00 | title=Polres Malang Tingkatkan Patroli di Titik Rawan Kriminalitas Jelang Idul Adha 2026
page=004 | date=2026-05-25T14:59:52+07:00 | title=Ditlantas Polda Jatim Bersama Satlantas Polres Malang Edukasi Keselamatan Berkendara di...
page=004 | date=2026-05-25T11:12:57+07:00 | title=BRI Kepanjen Gelar Sosialisasi Program Briguna Guna Mendukung Kebutuhan Finansial Pegawai
page=004 | date=2026-05-21T16:03:34+07:00 | title=Polres Malang Selidiki Penemuan Jasad Bayi Laki-laki di Pinggir Jalan
page=004 | date=2026-05-21T13:29:15+07:00 | title=Polres Malang: Di Hari Kebangkitan Nasional, Penyandang Disabilitas Dapat SIM D Gratis
page=004 | date=2026-05-20T14:54:33+07:00 | title=Kalapas Malang Bersama Forkopimda Kab Malang Ikut Musnahkan Barang Bukti di Kejari Kab ...
page=004 | date=2026-05-19T19:16:48+07:00 | title=Warga Binaan Lapas Malang Meninggal Dunia Akibat Serangan Jantung Setelah Ditangani Sec...
page=004 | date=2026-05-19T14:34:35+07:00 | title=Usai Aduan Masuk ke 110 Polres Malang Bakar Arena Judi Sabung Ayam
page=004 | date=2026-05-19T13:45:54+07:00 | title=Seorang Warga Binaan Lapas Malang Meninggal Dunia Lapas Masih Nunggu Hasil Medis
page=004 | date=2026-05-18T11:48:13+07:00 | title=Modus Pura-pura Belanja Pria Asal Tulungagung, Ditangkap Polres Malang
page=004 | date=2026-05-18T11:45:17+07:00 | title=Dua Pencuri Jeruk Diamankan Polres Malang, Satu Pelaku Residivis
page=004 | date=2026-05-13T15:40:17+07:00 | title=Polisi Bongkar Pembalakan Hutan di Perum Perhutani Malang Selatan
page=005 | date=2026-05-13T15:36:58+07:00 | title=Polres Malang Ringkus Dua Pemasok Sabu di Dampit
page=005 | date=2026-05-09T12:31:25+07:00 | title=Langkah Tegas Christo Menjadikan Lapas Malang Zero HALINAR Mengingatkan Sosok Heri Azhari
page=005 | date=2026-05-09T12:02:43+07:00 | title=Photo Booth Ramah Anak di KB Samsat Karangploso Disambut Antusias Wajib PKB
page=005 | date=2026-05-08T16:13:36+07:00 | title=Polres Malang Tetapkan 3 Tersangka Pasca Perusakan dan Kekerasan Terhadap Wisatawan di ...
page=005 | date=2026-05-06T11:06:17+07:00 | title=Pasca Keributan 31 Wisatawan Gathering Shopee Surabaya Positif Pakai Narkotika
page=005 | date=2026-05-05T15:34:36+07:00 | title=Berawal dari Nyanyian Arema Full of Site yang Dipelesetkan, Wisatawan Asal Surabaya Did...
page=005 | date=2026-05-05T12:08:45+07:00 | title=Polisi Selidiki Pasca Aksi Pengeroyokan kepada Wisatawan Asal Surabaya di Kawasan Panta...
page=005 | date=2026-05-05T11:03:18+07:00 | title=Christo Kuatkan Kinerja SDM yang Profesional Dilingkungan Lapas Kelas 1 Malang
page=005 | date=2026-05-05T10:14:46+07:00 | title=Dua Pengedar Sabu di Dampit di Bekuk Satresnarkoba Polres Malang
page=005 | date=2026-05-05T10:12:25+07:00 | title=DPO Curanmor Ditangkap Polisi Saat Nongkrong di Kepanjen
page=005 | date=2026-05-04T12:27:11+07:00 | title=Samsat Talangagung Tetap Berikan Pelayanan Maksimal dengan Ratusan Wajib PKB Antri Saat...
page=005 | date=2026-05-04T12:19:43+07:00 | title=Tingkatkan Pelayanan, Samsat Karangploso Buka Layanan Samsat Walk Thru untuk Pembayaran...
page=005 | date=2026-04-30T12:10:56+07:00 | title=Jelang Hari Buruh Nasional, Polres Malang Rangkul Elemen Organisasi Kemasyarakatan untu...
page=006 | date=2026-04-29T00:32:31+07:00 | title=Sebanyak 2.397 Narapidana Lapas Malang Dinyatakan MemilikiNIK yang Valid
page=006 | date=2026-04-28T12:04:48+07:00 | title=Melalui Program TJSL, BRI Dukung Layanan Kesehatan 1.200 Santri Melalui Bantuan 1 Unit ...
page=006 | date=2026-04-27T20:41:32+07:00 | title=Lepas dari Sorotan Media, Lapas Malang Beri Bantuan Gerobak Keluarga Warga Binaan di HB...
page=006 | date=2026-04-27T14:02:27+07:00 | title=KKI Kab Malang Peringati Hari Kartini dengan Berkunjung ke Candi Kidal
page=006 | date=2026-04-24T16:22:27+07:00 | title=Polres Malang Bongkar Penjualan LPG 3 Kg Ilegal dengan Tiga Tersangka
page=006 | date=2026-04-24T09:58:42+07:00 | title=Danlanud Abd Saleh Terima Brevet Setia Waspada Pengamanan VVIP
page=006 | date=2026-04-22T23:44:46+07:00 | title=Kalapas Klas 1 Malang Christo Siap Ubah Mindset Internal, yang Tidak Bisa Dibina Segera...
page=006 | date=2026-04-22T14:23:30+07:00 | title=Kartini Hadir di Tengah Pelayanan Satpas SIM Prototype Polres Malang
page=006 | date=2026-04-21T15:06:14+07:00 | title=Kenang Jasa RA Kartini KB, Samsat Karangploso Bagi-bagi Bunga kepada Wajib Pajak
page=006 | date=2026-04-20T13:59:08+07:00 | title=Kalapas Kelas 1 Malang Christo : Jangan Jadi Pengkhianat Organisasi
page=006 | date=2026-04-18T21:51:29+07:00 | title=Terapkan Komitmen Bersama Polres Malang Amankan 54 Oknum Suporter yang Membawa Miras
page=006 | date=2026-04-17T22:10:04+07:00 | title=Kalapas Malang Teguh Pamuji Resmi Geser Jadi Pembina Keamanan Pemasyarakatan Digantikan...
page=006 | date=2026-04-13T09:04:46+07:00 | title=Sindikat Curanmor Sekeluarga di Area Persawahan Diamankan Polres Malang
page=007 | date=2026-04-12T21:09:00+07:00 | title=Teguh Pamuji Bungkam soal Tes Urine di Lapas Kelas 1 Malang Tidak Gandeng BNN
page=007 | date=2026-04-11T20:44:48+07:00 | title=Menteri IMIPAS Tegaskan Komitmen Berantas Peredaran Narkotika dengan Mengandeng BNN dan...
page=007 | date=2026-04-11T08:11:56+07:00 | title=Sempat Viral, 3 Tersangka Pembobolan SMPN 1 Pakisaji Diamankan Polres Malang
page=007 | date=2026-04-10T12:06:48+07:00 | title=Perketat Pengamanan Setiap Blok Hunian, Lapas Kelas 1 Malang Gelar Razia Gabungan
page=007 | date=2026-04-08T17:13:49+07:00 | title=Pria Bobol Rumah Saat Salat Idul Fitri Akhirnya Tertangkap Polres Malang
page=007 | date=2026-04-08T17:09:34+07:00 | title=Polres Malang Tetapkan Satu Tersangka Kasus Kekerasan Seksual Anak
page=007 | date=2026-04-04T11:24:12+07:00 | title=Ratusan Personel Diturunkan Polres Malang Pastikan Ibadah Paskah Berjalan Aman
page=007 | date=2026-04-03T13:32:14+07:00 | title=Di Kota Malang, Akibat Sopir Ngantuk Truk Oleng Menabrak Median Jalan Hingga Terbalik
page=007 | date=2026-04-02T19:10:09+07:00 | title=Kapolres Malang : Keberadaan Dai Kamtibmas Salah satu Kekuatan Besar Dalam Menjaga Kamt...
page=007 | date=2026-04-02T10:03:50+07:00 | title=Perkuat Komitmen Laga Damai di Kanjuruhan, Polda Jatim Satukan Persebaya dan Arema
page=007 | date=2026-03-31T17:37:46+07:00 | title=Seorang Istri Warga Binaan Lapas Malang Diamankan Saat Mencoba Menyeludupkan Hp Buat Sa...
page=007 | date=2026-03-30T17:11:18+07:00 | title=Pasca Lebaran Idul Fitri 2026, Kapolres Malang Ajak Personel Perkuat Silaturahmi
page=007 | date=2026-03-30T17:09:21+07:00 | title=Polres Malang Mencatat Kendaraan Naik 34 Persen di Lebaran Idul Fitri 2026
page=008 | date=2026-03-28T09:50:30+07:00 | title=Jenguk Saudara Sakit di Bali, Mobil Anggota Polres Malang Dirusak Massa Akibat Ulah Deb...
page=008 | date=2026-03-25T15:14:00+07:00 | title=Polres Malang Tetap Siaga Hadapi Arus Balik Pemudik dan Wisatawan pada H+5 Lebaran
page=008 | date=2026-03-25T14:16:53+07:00 | title=Segilitir Anggota Satlantas Polres Malang Mampu Atur Arus Ribuan Wisatawan Menuju Bromo
page=008 | date=2026-03-24T17:24:50+07:00 | title=Kinerja Polantas Saat Mengatur Arus Lalin Lebaran 2026 Dapat Apresiasi Turis Asal Amerika
page=008 | date=2026-03-24T13:37:44+07:00 | title=Polres Malang : Libur Lebaran Ramai, Polisi Tingkatkan Pengamanan di Tempat Wisata
page=008 | date=2026-03-24T13:33:58+07:00 | title=Polres Malang : H+4 Lebaran Volume Kendaraan Meningkat, Polisi Siaga di Jalur Wisata Ma...
page=008 | date=2026-03-23T18:44:55+07:00 | title=H+3 Lebaran, Arus Kendaraan di Tol Malang Melonjak Hingga 40 Persen
page=008 | date=2026-03-23T18:41:23+07:00 | title=H+3 Lebaran, Polres Malang Perketat Pengamanan Menuju Wisata Bromo
page=008 | date=2026-03-22T22:43:48+07:00 | title=Polres Malang : 48 Motor dan 8 Mobil Dititipkan Pemudik Lebaran Idul Fitri 1447 H
page=008 | date=2026-03-20T17:34:25+07:00 | title=Polres Malang: H-1 Lebaran, Arus Tol Malang Menurun Polisi Tetap Siaga
page=008 | date=2026-03-20T10:51:49+07:00 | title=H-2 Lebaran Polres Malang Bingkisan Lebaran untuk Komunitas Ojek Online
page=008 | date=2026-03-20T10:49:17+07:00 | title=Polres Malang Prediksi Arus Puncak Mudik di Tol Malang Masih Tinggi Termasuk H- Lebaran
page=008 | date=2026-03-18T18:58:10+07:00 | title=Ketua Bhayangkari Cabang Malang Ikut Bagikan Bingkisan Lebaran ke Petugas Pospam dan Po...
page=009 | date=2026-03-18T18:54:08+07:00 | title=Jelang Akhir Ramadan, Polres Malang Konsisten Bagikan Takjil untuk Pengendara
page=009 | date=2026-03-17T16:55:23+07:00 | title=Polisi Selidiki Ruko Laundry di Kab Malang Terbakar, Tewaskan Satu Orang
page=009 | date=2026-03-17T16:50:38+07:00 | title=Pastikan Angkutan Mudik Layak Jalan Bus di Terminal Talangagung Jalani Ramp Check
page=009 | date=2026-03-16T21:09:57+07:00 | title=Jelang Lebaran Lapas Malang Ajak Keluarga Warga Binaan Buka Puasa Bersama
page=009 | date=2026-03-16T14:14:00+07:00 | title=Jelang Lebaran Stasiun dan Terminal Jadi Sasaran Pengamanan Polres Malang
page=009 | date=2026-03-16T14:11:23+07:00 | title=Arus Mudik di Pintu Tol Malang Mulai Meningkat, Polisi Perkuat Gaturlantas
page=009 | date=2026-03-14T15:56:56+07:00 | title=Demi Kelancaran Arus Mudik Lebaran, Polres Malang Siapkan 8 Pos Pengamanan
page=009 | date=2026-03-14T15:53:54+07:00 | title=Mudik Aman, Polres Malang Ajak Masyarakat Manfaatkan Call Center 110 Polri
page=009 | date=2026-03-13T20:56:14+07:00 | title=Kadisops Lanud Abd Saleh Pimpin Apel Pengamanan Angkutan Lebaran 2026
page=009 | date=2026-03-13T14:55:09+07:00 | title=Polres Malang Berbagi Berkah di Bulan Ramadan dengan Menggelar Pangan Murah
page=009 | date=2026-03-12T21:02:18+07:00 | title=1.659 Botol Miras Hasil Operasi Pekat Semeru 2026 Dimusnahkan Polres Malang
page=009 | date=2026-03-12T20:59:22+07:00 | title=Korban Curanmor di Malang Mendapatkan Kembali Sepeda Motornya yang Hilang
page=009 | date=2026-03-12T18:58:19+07:00 | title=Polres Malang Ungkap 26 Kasus Curanmor dengan 38 Motor Berhasil Disita
page=010 | date=2026-03-12T18:41:21+07:00 | title=Eratkan Kebersamaan, Lapas Malang Ajak Media Lapas Bersatu Buka Puasa Bersama
page=010 | date=2026-03-11T12:56:23+07:00 | title=Satgas Pangan Polres Malang Pastikan Bahan Pokok Aman Jelang Lebaran Idul Fitri 2026
page=010 | date=2026-03-11T12:52:51+07:00 | title=Polres Malang Gelar Latpraops Ketupat 2026 Persiapan Pam Lebaran Idul Fitri
page=010 | date=2026-03-10T20:58:05+07:00 | title=Judi Sabung Ayam di Bulan Ramadhan Marak di Kab Malang
page=010 | date=2026-03-09T15:29:45+07:00 | title=Kembali Polres Malang Bakar Sarana Judi Sabung Ayam di Gedangan
page=010 | date=2026-03-09T12:21:03+07:00 | title=Pelaku Perampasan Sepeda Motor dengan Sajam Diringkus Polres Malang
page=010 | date=2026-03-09T12:16:35+07:00 | title=Warga Kab Nganjuk Ditangkap Warga Saat Ketahuan Mencuri Sepeda Motor
page=010 | date=2026-03-09T12:12:51+07:00 | title=Gadaikan Motor Milik Orang Lain, Warga Turen Diamankan Polisi Polres Malang
page=010 | date=2026-03-08T21:13:58+07:00 | title=Untuk Sekian Kalinya Arena Sabung Ayam di Bongkar Polres Malang Tanpa Satu pun Tersangk...
page=010 | date=2026-03-07T23:34:24+07:00 | title=Kapolres Malang Bersama Ketua Bhayangkari Sapa Pengendara Sambil Bagikan Takjil Ramadan
page=010 | date=2026-03-06T16:20:38+07:00 | title=Polisi Gadungan Perampas Mobil Diringkus Polres Malang
page=010 | date=2026-03-06T10:42:32+07:00 | title=Safari Ramadan di Lapas Kelas 1 Malang Sarana Perkuat Kepedulian Sosial
page=010 | date=2026-03-05T14:26:18+07:00 | title=Polres Malang dan Polsek : Buka Layanan Titip Kendaraan Gratis Lebaran Idul Fitri 2026
page=011 | date=2026-03-04T17:52:19+07:00 | title=Tekan Tingkat Kriminal, Polres Malang Tingkatkan Patroli di Bulan Ramadhan
page=011 | date=2026-03-01T13:50:54+07:00 | title=Motor Mahasiswa Dicuri, Polres Malang Ringkus Pelaku Saat Jual COD
page=011 | date=2026-02-28T19:01:34+07:00 | title=Ramadan Berkah, Polres Malang Bagikan Ratusan Takjil ke Pengguna Jalan
total rows: 130
first page: 1
last page: 11
newest date: 2026-06-26 13:15:52
oldest date: 2026-02-28 19:01:34
cutoff date: 2026-02-28 12:19:25.879283
reached cutoff: False
null parsed dates: 0

rows per month:

     month  count
0  2026-02      1
1  2026-03     44
2  2026-04     24
3  2026-05     30
4  2026-06     31

rows per page:

    page_num  rows              newest              oldest
0          1    10 2026-06-26 13:15:52 2026-06-19 10:14:25
1          2    13 2026-06-18 14:21:21 2026-06-05 16:26:49
2          3    13 2026-06-05 10:00:20 2026-05-26 20:36:41
3          4    13 2026-05-26 20:27:45 2026-05-13 15:40:17
4          5    13 2026-05-13 15:36:58 2026-04-30 12:10:56
5          6    13 2026-04-29 00:32:31 2026-04-13 09:04:46
6          7    13 2026-04-12 21:09:00 2026-03-30 17:09:21
7          8    13 2026-03-28 09:50:30 2026-03-18 18:58:10
8          9    13 2026-03-18 18:54:08 2026-03-12 18:58:19
9         10    13 2026-03-12 18:41:21 2026-03-05 14:26:18
10        11     3 2026-03-04 17:52:19 2026-02-28 19:01:34

## Save debug list CSV

In [6]:
df_to_save = live_df if 'live_df' in globals() and len(live_df) else local_df
OUTPUT_PATH.parent.mkdir(exist_ok=True)
df_to_save.to_csv(OUTPUT_PATH, index=False)
print('saved:', OUTPUT_PATH)

saved: /Users/tsar/Library/Mobile Documents/com~apple~CloudDocs/main/college/pkl/project/csv/memox_list_debug.csv

## Optional article sample check

In [7]:
sample_rows = (live_df if 'live_df' in globals() and len(live_df) else local_df).head(5)
article_rows = []
for index, row in sample_rows.iterrows():
    try:
        article = scraper.extract_article(row)
        article_rows.append(article)
        print(f"[{len(article_rows)}] content_len={len(article.get('content') or '')} | {short_title(article.get('title'))}")
    except Exception as error:
        print(f"failed sample article {index + 1}: {row.get('url')} | {error}")
article_df = pd.DataFrame(article_rows)
display(article_df[['title', 'published_date', 'content', 'url']].head() if len(article_df) else article_df)

[1] content_len=2158 | Usai Diresmikan Kapolres Malang Ratusan Jamaah Sholat Jumat Datangi Masjid Budi Trianti...
[2] content_len=3752 | Sambut Hari Bhayangkara ke-80 Polres Malang Bangun 7 Sumur Bor di 3 Kecamatan
[3] content_len=2538 | Giat Donor Darah Hari Bhayangkara ke-80 di Polres Malang Diikuti TNI dan Masyarakat Umum
[4] content_len=4218 | Mengaku Ajudan Gubenur Jatim, 2 Tersangka Kasus Penipuan Program UMKM Diamankan Polres ...
[5] content_len=2411 | Jelang Hari Bhayangkara ke-80, Kapolres Malang Pimpin Giat Ziarah dan Tabur Bunga di TMP

,title,published_date,content,url
0,Usai Diresmikan Kapolres Malang Ratusan Jamaah Sholat Jumat Datangi Masjid Budi Trianti Polsek Lawang,2026-06-26,MEMOX.CO.ID\n– Usai diresmikan Kapolres Malang AKBP M Taat Risdi Jum’at (26/06/26) ratusan jamaah sholat Jum’at mendatangi masjid Budi Trianti Polsek Lawang...,https://memox.co.id/usai-diresmikan-kapolres-malang-ratusan-jamaah-sholat-jumat-datangi-masjid-budi-trianti-polsek-lawang/
1,Sambut Hari Bhayangkara ke-80 Polres Malang Bangun 7 Sumur Bor di 3 Kecamatan,2026-06-25,"MEMOX.CO.ID\n– Polres Malang meresmikan tujuh titik bantuan sosial Sumur Bor Polri Presisi yang tersebar di wilayah Kecamatan Pagak, Donomulyo, dan Sumberma...",https://memox.co.id/sambut-hari-bhayangkara-ke-80-polres-malang-bangun-7-sumur-bor-di-3-kecamatan/
2,Giat Donor Darah Hari Bhayangkara ke-80 di Polres Malang Diikuti TNI dan Masyarakat Umum,2026-06-24,"MEMOX.CO.ID\n– Polres Malang menggelar kegiatan donor darah dalam rangka menyambut Hari Bhayangkara ke-80 di GOR Indoor Polres Malang, Rabu (24/6/2026).\nKe...",https://memox.co.id/giat-donor-darah-hari-bhayangkara-ke-80-di-polres-malang-diikuti-tni-dan-masyarakat-umum/
3,"Mengaku Ajudan Gubenur Jatim, 2 Tersangka Kasus Penipuan Program UMKM Diamankan Polres Malang",2026-06-24,MEMOX.CO.ID\n– Satreskrim Polres Malang membongkar dugaan tindak pidana penipuan berkedok program pengembangan UMKM yang juga mengaku ajudan Gubernur Jatim ...,https://memox.co.id/mengaku-ajudan-gubenur-jatim-2-tersangka-kasus-penipuan-program-umkm-diamankan-polres-malang/
4,"Jelang Hari Bhayangkara ke-80, Kapolres Malang Pimpin Giat Ziarah dan Tabur Bunga di TMP",2026-06-23,"MEMOX.CO.ID\n– Polres Malang menggelar ziarah rombongan di Taman Makam Pahlawan (TMP) Prayuda Nirwana, Kecamatan Kepanjen, Kabupaten Malang, dalam rangka me...",https://memox.co.id/jelang-hari-bhayangkara-ke-80-kapolres-malang-pimpin-giat-ziarah-dan-tabur-bunga-di-tmp/